mcallegari/qlcplus

fixtures/Robe-Pointe
Based on this specs: http://www.robe.cz/fileadmin/robe/downloads/dmx_charts/Robin_Pointe_DMX_charts.pdf
=> Add robe pointe

plugins/dmxusb/src/nanodmx.cpp, plugins/dmxusb/src/qlcftdi-libftdi.cpp
This is a patch to resolve the build issue for qlcplus on system wich use libftdi1 #435
=> fix build errors on system uses libftdi1

plugins/enttecwing/src/enttecwing.cpp, plugins/enttecwing/src/enttecwing.h, plugins/enttecwing/src/playbackwing.cpp, plugins/enttecwing/src/playbackwing.h, plugins/enttecwing/src/wing.cpp, plugins/enttecwing/src/wing.h
*removed the code of the older patches
*pageup/pagedown buttons now works inside the frame widget pages (only)
*go/back buttons now work
=> updated and cleaned playbackwing

resources/fixtures/Eurolite-LED-Flood-Light-252-RGB-19.qxf
I could not find this fixture so I created it with the fixture creator.
=> Add Eurolite-LED-Flood-Light-252-RGB-19

plugins/dmxusb/src/dmxusb.cpp, plugins/dmxusb/src/dmxusbconfig.cpp, plugins/dmxusb/src/dmxusbwidget.h, plugins/dmxusb/src/euroliteusbdmxpro.cpp, plugins/dmxusb/src/euroliteusbdmxpro.h, plugins/dmxusb/src/qlcftdi-ftd2xx.cpp, plugins/dmxusb/src/qlcftdi-libftdi.cpp, plugins/dmxusb/src/qlcftdi.h, plugins/dmxusb/src/src.pro, plugins/dmxusb/src/z65-dmxusb.rules
The plugin has been tested on Ubuntu 14.04 amd64 only. Reading the serial number with ENTTEC protocol did not work so I omitted that part.
Cheers,
Karri Kaksonen
=> Eurolite USB DMX512 Pro plugin

plugins/dmxusb/src/euroliteusbdmxpro.cpp, plugins/dmxusb/src/src.pro
add missing ifdef in euroliteusbdmxpro.cpp
reorder package detection in dmxusb plugin
Will merge right after travis' green light.
=> fix build on fedora 21

debian/changelog, engine/src/doc.cpp, engine/src/doc.h, engine/src/fixture.cpp, ui/src/fixturemanager.cpp
when changing the universe of fixtures
Doc: address hash only updated by slotFixtureChanged
Doc: removed moveFixture and changeFixtureMode (not necessary)
Slight modification of #471
=> fixed simpledesk shows wrong fixtures or crashing

ui/src/qlcplus_fr_FR.ts, webaccess/src/webaccess_fr_FR.ts
Sorry for the big late in translations...
=> Update French translations

engine/src/chaserrunner.cpp, engine/src/cuestack.cpp, engine/src/efxfixture.cpp, engine/src/function.cpp, engine/src/mastertimer.cpp, engine/src/mastertimer.h, engine/src/scene.cpp, engine/test/chaser/chaser_test.cpp, engine/test/chaser/chaser_test.h, engine/test/mastertimer/mastertimer_stub.cpp
This fixes the issue "scene in a very quick chaser may stay ON after the end of the chaser"
=> Function startstop 09

plugins/hid/HID_ca_ES.ts
Updated catalan translation HID plugin
=> Update catalan translation

plugins/artnet/src/ArtNet_ca_ES.ts
Updated Artnet plugin catalan translation
=> Updated Artnet plugin catalan translation

plugins/E1.31/E131_ca_ES.ts, plugins/artnet/src/ArtNet_ca_ES.ts, plugins/osc/OSC_ca_ES.ts
Update catalan translation ArtNet, E1.31 and OSC plugins
=> Update catalan translation ArtNet, E1.31 and OSC plugins

plugins/E1.31/E131_de_DE.ts, plugins/artnet/src/ArtNet_de_DE.ts, plugins/osc/OSC_de_DE.ts
=> Update german translations

plugins/artnet/src/ArtNet_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Updated UI and Arnet Catalan translation
=> Updated UI and Arnet Catalan translation

ui/src/collectioneditor.cpp, ui/src/collectioneditor.h, ui/src/collectioneditor.ui
In this pull request I have implemented the test button for collections.
This is very usefull to test collections directly from editor.
=> Add test button to Collection

plugins/E1.31/E131_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Updated catalan translation E1.31 plugin and UI.
=> Updated catalan translation

resources/fixtures/Ayra-ComPar20.qxf
Fixture definition for the Ayra ComPar20
=> Add fixture Ayra ComPar20

etc/qlcplus-fixtureeditor.desktop, etc/qlcplus.desktop
- Remove carriage returns
- Use standard category names from
http://standards.freedesktop.org/menu-spec/menu-spec-1.0.html
=> Make Linux desktop files Freedesktop compliant

debian/changelog, ui/src/virtualconsole/vccuelist.cpp, ui/src/virtualconsole/vccuelist.h, ui/src/virtualconsole/vccuelistproperties.cpp, ui/src/virtualconsole/vccuelistproperties.ui, ui/test/vccuelist/vccuelist_test.cpp
This allows to change the behavior of the next/prev buttons
while the chaser is not running.
http://qlcplus.org/forum/viewtopic.php?f=5&t=8694
=> Cue List: Can change next/prev buttons behavior

ui/src/qlcplus_ca_ES.ts
Updated UI catalan translation.
=> Updated UI catalan translation.

resources/fixtures/Contest-MiniCube-6TCb.qxf
=> New fixture - Contest-MiniCube-6CTb

resources/fixtures/Chauvet-Intimidator-Wave-360-IRC.qxf, resources/fixtures/Contest-MiniCube-6TCb.qxf
=> New fixture - Chauvet Intimidator Wave 360 IRC

resources/fixtures/Eurolite-LED-FE-1500.qxf
=> New fixture - Eurolite LED FE-1500

resources/fixtures/Eurolite-LED-FE-1500.qxf, resources/fixtures/Lightronics-FXLD618C2I.qxf
The part number ends in I, not 1 (one).
=> New fixture - Lightronics FXLD618C2I

resources/fixtures/Eurolite-LED-FE-1500.qxf, resources/fixtures/JB-Systems-COB-4BAR.qxf, resources/fixtures/Lightronics-FXLD618C2I.qxf
=> New fixture - JB Systems COB-4BAR

resources/fixtures/American-DJ-Fog-Fury-Jett.qxf, resources/fixtures/Eurolite-LED-FE-1500.qxf, resources/fixtures/JB-Systems-COB-4BAR.qxf, resources/fixtures/Lightronics-FXLD618C2I.qxf
Created on 01/09/15.
Modifed to add RGBA colour macros with debatable mapping to RGB values.
=> New fixture - American DJ Fog Fury Jett

resources/fixtures/Eurolite-LED-KLS-401.qxf
Created on 04/09/15.
Red and green on head 1 are multipurpose so the channels are effect, not intensity. The effect colours are correct however.
=> New fixture - Eurolight LED KLS-401

resources/fixtures/Varytec-LED-PAR56.qxf
Fixture created on 18/07/15.
Added alternate functions for numerous channels.
Datasheet here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8740
=> New ficture - Varytec LED PAR56

resources/fixtures/Eurolite-TB-250.qxf, resources/fixtures/Varytec-LED-PAR56.qxf
Created on 30/07/15
Datasheet:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8778
=> New fixture - Eurolite TB-250

resources/fixtures/ProLights-UVStrip18.qxf
Fixture created on 23/08/15.
Manual link here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8831
=> New fixture - ProLights UVStrip18

resources/fixtures/American-DJ-Inno-Pocket-Beam-Q4.qxf
Created on 24/08/15.
Minor change to Shutter/Strobe channel description.
=> New fixture - American DJ Inno Pocket Beam Q4

resources/fixtures/ProLights-SmartBat.qxf
Created on 01/09/15
Minor corrections to capability names and descriptions.
Link to manual here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8859
=> New fixture - ProLights SmartBat

resources/fixtures/Robe-ClubWash-600-CT.qxf
Created on 06/09/15
Nearly every capability did not match the datasheet in some way so all had to be changed from the original post:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8884
http://www.robe.cz/it/support/list-files/15/file-detail/4509/file-cat/robe-downloads/
=> New fixture - Robe ClubWash 600 CT

resources/fixtures/Futurelight-DJ-HEAD-575-SPOT.qxf
Created on 10/09/15.
Gobo images unknown at present. Original post almost unaltered:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8897
=> New fixture - Futurelight DJ-HEAD 575 SPOT

resources/fixtures/American-DJ-Mega-TriPar-Profile-Plus.qxf
Existing near identical fixture (Mega Par Profile Plus) modified to reflect different physical properties.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8898
=> New fixture - American DJ Mega TriPar Profile Plus

resources/fixtures/Chauvet-Intimidator-Wash-Zoom-350-IRC.qxf
Created on 16/09/15.
Datasheet etc.:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=8923&p=38983#p38983
=> New fixture - Chauvet Intimidator Wash Zoom 350 IRC

resources/fixtures/Equinox-Party-Par-LED-PAR-56.qxf
Requested on 24/08/15. The manual is very basic.
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=8839
=> New fixture - Equinox Party Par LED PAR 56

resources/fixtures/Robe-Robin-MiniMe.qxf
Created on 16/09/15.
I can no longer see so please put an evening aside to check this.
http://www.robe.cz/products/article/robin-minime/#downloads
=> New fixture - Robe Robin MiniMe

plugins/osc/OSC_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Updated catalan translation UI and OSC plugin
=> Updated catalan translation UI and OSC plugin

plugins/E1.31/configuree131.cpp, plugins/E1.31/configuree131.h, plugins/E1.31/configuree131.ui, plugins/E1.31/e131controller.cpp, plugins/E1.31/e131controller.h, plugins/E1.31/e131packetizer.cpp, plugins/E1.31/e131plugin.cpp, plugins/E1.31/e131plugin.h
- Allow unicast input and output
- Configure unicast output port and input port
- Allow changing E1.31 universe for input and output
Tests done:
- Unicast input/output seem OK
- Multicast output seems OK
- Multicast input : not tested
=> E131 unicast configuration

resources/fixtures/Blizzard-Lighting-HotBox-Infiniwhite.qxf, resources/fixtures/Blizzard-Lighting-RokBox-Infiniwhite.qxf, resources/fixtures/Chauvet-COREpar-80.qxf, resources/fixtures/GLX-Lighting-Power-LED-Beam-38-Narrow.qxf
Created here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8950
Added physical data and small corrections.
=> New fixture - Blizzard Lighting HotBox Infiniwhite

resources/fixtures/Blizzard-Lighting-HotBox-Infiniwhite.qxf, resources/fixtures/Blizzard-Lighting-RokBox-Infiniwhite.qxf, resources/fixtures/Chauvet-COREpar-80.qxf, resources/fixtures/PR-Lighting-Pilot-575.qxf
Datasheet here:
http://omnisistem.com/download/manuals/lighting%20/PR-Pilot575.pdf
=> New fixture - PR Lighting Pilot 575

resources/fixtures/Blizzard-Lighting-HotBox-Infiniwhite.qxf, resources/fixtures/Blizzard-Lighting-RokBox-Infiniwhite.qxf, resources/fixtures/Chauvet-COREpar-80.qxf, resources/fixtures/GLX-Lighting-Power-LED-Beam-38-Narrow.qxf, resources/fixtures/Stairville-DJ-Lase-150-RGY-MkII.qxf
Original request here:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=8955
=> New fixture - Stairville DJ Lase 150 RGY MkII

resources/fixtures/Blizzard-Lighting-HotBox-Infiniwhite.qxf, resources/fixtures/Blizzard-Lighting-RokBox-Infiniwhite.qxf, resources/fixtures/Chauvet-COREpar-80.qxf, resources/fixtures/GLX-Lighting-Power-LED-Beam-38-Narrow.qxf, resources/fixtures/JB-Systems-Dynaspot.qxf
Link to datasheet:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=8957
=> New fixture - JB Systems Dynaspot

resources/fixtures/Cameo-CL-Superfly-HP.qxf
Link:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8749&p=38038&hilit=cameo+SUPERFLY#p38038
=> New Fixture - Cameo CL Superfly HP

plugins/E1.31/E131_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Updated catalan translation (UI + E1.31)
=> Updated catalan translation (UI + E1.31)

resources/fixtures/American-DJ-Hyper-Gem-LED.qxf
Hopefully v2 of this fixture PR should work OK.
=> New fixture - American-DJ-Hyper-Gem-LED

etc/qlcplus-fixtureeditor.desktop, etc/qlcplus.desktop, etc/qlcplus.xml
- qlcplus.xml
- qlcplus.desktop
- qlcplus-fixtureeditor.desktop
=> Spanish Translation

etc/qlcplus.xml
Add missing spanish translation strings in qlcplus.xml
=> Translation

etc/qlcplus-fixtureeditor.desktop, etc/qlcplus.desktop, etc/qlcplus.xml
Catalan translation qlcplus.xml, qlcplus.desktop, qlcplus.fixtureeditor
=> Catalan translation qlcplus.xml, qlcplus.desktop, qlcplus.fixtureeditor

resources/fixtures/American-DJ-Event-Bar-Q4.qxf
Original post here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8978
There were channels missing, no physical data and incorrect channel types.
There are two versions of this fixture with different capabilities. It is possible to use both by selecting the required mode.
=> New fixture - American DJ Event Bar Q4

resources/fixtures/Robe-ColorSpot-575-AT.qxf
Manual here:
http://www.robe.cz/nc/support/file-detail/4723/
Requested here:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=8993
This is similar to the Robe Robin 300E Beam for which I'm still waiting confirmation of the channels:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8987
=> New fixture - Robe ColorSpot 575 AT

resources/fixtures/Proel-PLLED64RGB.qxf
Simple fixture:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8988
=> New fixture - Proel PLLEDP64RGB

ui/src/qlcplus_ca_ES.ts
Updated Catalan Translation (UI)
=> Updated Catalan Translation (UI)

ui/src/qlcplus_ca_ES.ts
Revised and corrected some errors detected.
=> Catalan Translation. Revised and corrected some errors detected.

plugins/dmxusb/src/DMX_USB_ca_ES.ts, plugins/gpio/GPIO_ca_ES.ts, plugins/uart/UART_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Update Catalan Translation. (UI, GPIO, UART, DMX_USB)
=> Update Catalan Translation. (UI, GPIO, UART, DMX_USB)

resources/fixtures/Electroconcept-SPC029.qxf
Not changed apart from adding Master Dimmer to the multi-head modes.
=> New fixture - Electroconcept-SPC029

resources/fixtures/Microh-Plasmawave-1-RGB.qxf
Standard laser fixture:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9028
=> New fixture - Microh-Plasmawave-1-RGB

resources/fixtures/JB-Systems-Lounge-Laser-DMX.qxf
Requested here (datasheet link on right of screen after following link):
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9052
=> New fixture - JB-Systems-Lounge-Laser-DMX

resources/fixtures/JB-Systems-Super-Solar-RGBW.qxf
Request
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9051
Datsheet on right after following link in post.
=> New fixture - JB-Systems-Super-Solar-RGBW

resources/fixtures/American-DJ-Starburst.qxf
Please check channel 6. I've used UV instead of purple as it is the nearest colour. It would be nice to select a generic colour instead of the fixed ones available.
http://www.americandj.eu/en/starburst.html
=> New fixture - American-DJ-Starburst

resources/fixtures/Chauvet-LED-PAR-64-Tri-B.qxf
Same functionality as Chauvet SlimPAR 64 so copied it.
=> New fixture - Chauvet-LED-PAR-64-Tri-B

resources/fixtures/BoomToneDJ-Strob-LED-18.qxf
Posted on forum with datasheet, Mon Oct 26th.
=> New fixture - BoomToneDJ-Strob-LED-18

resources/fixtures/Stairville-xBrick-Full-Colour-16X3W.qxf
This fixture has been updated with correct heads and and more appropriate colour channels for the 5-channel mode. Master Dimmer also added to the heads.
=> Updated fixture - Stairville-xBrick-Full-Colour-16X3W

fixtureeditor/fixtureeditor_ca_ES.ts, plugins/E1.31/E131_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Some misspelled words and items revised.
=> Catalan Translation.

resources/fixtures/BoomToneDJ-Froggy-LED-RGBW.qxf
Fixture Definitions, Oct 26th for datasheet.
=> New fixture - BoomToneDJ-Froggy-LED-RGBW

resources/fixtures/iSolution-iMove-250w.qxf
Datasheet here (Uploaded Oct 25th):
www.maxlight.ru/downloads/acme/imove-250w.pdf
=> New fixture - iSolution-iMove-250W

resources/fixtures/Chauvet-ColorStrip-Mini.qxf
Added physical data and fixed multi-purpose channels. Datasheet from google:
chauvet colorstrip mini manual
=> Fixture update - Chauvet-ColorStrip-Mini

resources/fixtures/Chauvet-CORE-3x3.qxf
Added physical data to 2 modes and corrected channel order in 9-channel mode.
http://www.chauvetlighting.co.uk/core-3x3.html
=> Fixture update - Chauvet-CORE-3x3

resources/fixtures/Chauvet-Intimidator-Scan-LED-200.qxf
Missing physical info added to 5-channel mode.
http://www.chauvetlighting.com/intimidator-scan-led-200.html
=> Fixture update - Chauvet-Intimidator-Scan-LED-200

resources/fixtures/Chauvet-Intimidator-Spot-LED-250.qxf
Update physical info.
http://www.chauvetlighting.co.uk/intimidator-spot-led-250.html
=> Fixture update - Chauvet-Intimidator-Spot-LED-250

resources/fixtures/Chauvet-LEDrain64.qxf
Added physical data and updated macro colours channel with the values.
Google datasheet:
chauvet LEDrain 64
=> Fixture update - Chauvet-LEDrain64

resources/fixtures/Chauvet-LED-Splash-86b.qxf
Added physical data.
google for datasheet
chauvet led splash 86b
=> Fixture update - Chauvet-LED-Splash-86b

resources/fixtures/Chauvet-SlimPAR-56.qxf
Physical data updated.
http://www.chauvetlighting.co.uk/slim-par-56.html
=> Fixture update - Chauvet-SlimPAR-56

resources/fixtures/Coemar-Stage-Lite-LED.qxf
Added physical data.
Datasheet Google:
coemar stage lite led
=> Fixture update - Coemar-Stage-Lite-LED

resources/fixtures/Futurelight-PHW-700.qxf
Added physical data, missing channel (12) and corrected Pan/tilt speed channel etc. etc.
Data from google search.
=> Fixture update - Futurelight-PHW-700

resources/fixtures/Stairville-LED-PAR56.qxf
Added physical info using QLC+ 14.10.1
=> Fixture update - Stairville-LED-PAR56

resources/fixtures/Laserworld-ES-600B.qxf
Added physical data. Several channels had incorrect ranges for functions
Google for datasheet
laserworld es 600b manual
=> Fixture update - Laserworld-ES-600B

resources/fixtures/SGM-Victory-II-250.qxf
Added gobo images to gobo channel (same as Victory Mk1 so simple addition)
=> Fixture update - SGM-Victory-II-250

resources/fixtures/SGM-Victory-II-Pro150.qxf
Mechanical data and gobos/colours added,
Google:
sgm victory ii pro 150 manual
=> Fixture update - SGM-Victory-II-Pro150

resources/fixtures/Martin-Destroyer.qxf
Added physical data.
Google:
martin destroyer manual
=> Fixture update - Martin-Destroyer

fixtureeditor/fixtureeditor_cz_CZ.ts, plugins/E1.31/E131_cz_CZ.ts, plugins/dmxusb/src/DMX_USB_cz_CZ.ts, plugins/gpio/GPIO_cz_CZ.ts, plugins/hid/HID_cz_CZ.ts, plugins/loopback/src/loopback_cz_CZ.ts, plugins/osc/OSC_cz_CZ.ts, plugins/uart/UART_cz_CZ.ts, resources/fixtures/Contest-Evora-DUO-B2R.qxf, resources/fixtures/Contest-Oz-37x15QC.qxf, resources/fixtures/Evora-Beam-15R.qxf, resources/fixtures/Evora-Beam-5R.qxf, webaccess/src/webaccess_cz_CZ.ts
Contest Evora DUO B2R
Contest Oz 37x15QC
Evora Beam 15R
Evora Beam 5R
=> Added few fixtures

resources/fixtures/SGM-Giotto-Wash-400.qxf
Physical data added and click and go colours/rainbow speeds added.
Datasheet
http://sgmlight.com/products/giotto-wash-400/c-23/p-108#
=> Fixture update - SGM-Giotto-Wash-400

resources/fixtures/SGM-Giotto-Spot-250.qxf
Added gobos and colours and physical data. Two of the gobos (6 and 7) are approximates but better than nothing to me.
Google search to manual (Italian only but hey):
sgm giotto spot 250 manual
=> Fixture update - SGM-Giotto-Spot-250

resources/fixtures/SGM-Colorlab-250.qxf
Added physical data, click and go colours and correct gobos.
Google this for Italian manual
sgm colorlab 250
=> Fixture update - SGM-Colorlab-250

resources/fixtures/GLP-Junior-Scan-2.qxf
Update physical data/gobos/colours as per Junior Scan 1.
Datasheet:
http://www.glp.de/index.php?id=254&L=1#2
=> Fixture update - GLP-Junior-Scan-2

resources/fixtures/American-DJ-Inno-Pocket-Roll.qxf
Updated physical data. Not really a moving head in the usual sense.
Manual: ADJ
=> Fixture update - American-DJ-Inno-Pocket-Roll

resources/fixtures/American-DJ-Inno-Pocket-Scan.qxf
Updated physical data - Actual pan/tilt data not available so taken from images of the device in use.
=> Fixture update - American-DJ-Inno-Pocket-Scan

resources/fixtures/Eurolite-KLS200.qxf
Updated physical data, corrected strobe channel.
https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CCgQFjABahUKEwi05szCkfnIAhXJAxoKHZl_Ca0&url=https%3A%2F%2Fimages.static-thomann.de%2Fpics%2Fatg%2Fatgdata%2Fdocument%2Fmanual%2F231402_eurolite_kls_200.pdf&usg=AFQjCNEO66oAe14LzM9EMkioAMy6rxpcgQ&sig2=DA5JbLNAEjfxzERqRFvDww&cad=rja
=> Fixture update - Eurolite-KLS200

resources/fixtures/Robe-ClubSpot-250CT.qxf
Added physical data and click and go colours. No similar gobos found,
http://www.robe.cz/products/discontinued/article/clubspot-250-ct/#downloads
=> Fixture update - Robe-ClubSpot-250CT

resources/fixtures/Blizzard-Lighting-Lil-G.qxf
There is a 'cut sheet' link showing some gobos for this but there are only 7 (out of 9) and no info on the order of them, so they're blank.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9124
http://www.blizzardlighting.com/products/moving-head-lights/item/176-lil-g
=> New fixture - Blizzard-Lighting-Lil-G

resources/fixtures/Blizzard-Lighting-Pixellicious.qxf
480 channel mode is done with the RGB panel.
http://www.blizzardlighting.com/products/par-cans-and-wash-lights/item/273-pixellicious
=> New fixture - Blizzard lighting pixellicious

resources/fixtures/Blizzard-Lighting-Lo-Pro-CSI.qxf
Added heads to the fixture from the original. This UV lamp is listed as an 'effect' by the author. It's not a colour 'changer' after all...
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9124
http://www.blizzardlighting.com/products/led-strobes-blacklights/item/196-lo-pro
=> New fixture - Blizzard-Lighting-Lo-Pro-CSI

ui/src/virtualconsole/vcslider.cpp
http://qlcplus.org/forum/viewtopic.php?f=5&t=9131
=> Fix forced LTP channel being forcefully controlled by a level mode VCSlider

resources/fixtures/Cameo-Multi-PAR-3.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9141&p=40221#p40221
=> New fixture - Cameo-Multi-PAR-3

resources/fixtures/HQ-Power-VDPL110CC-LED-Tri-Spot.qxf
Is this Velleman or 'HQ Power'? It's both...
Manual linked to here:
http://www.hqpower.eu/products/view/?country=be&lang=en&id=386168
=> New fixture - HQ-Power-VDPL110CC-LED-Tri-Spot

engine/src/chaserrunner.cpp, ui/src/virtualconsole/vccuelist.cpp, ui/src/virtualconsole/vccuelist.h
=> Cuelist crossfade fix

resources/fixtures/Showtec-LED-Pixel-Track-Pro.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9174&p=40399#p40399
=> New fixture - Showtec-LED-Pixel-Track-Pro

resources/fixtures/Showtec-Power-Spot-9-Q6-Tour-V1.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9196&p=40419#p40419
=> New fixture - Showtec-Power-Spot-9-Q6-Tour-V1

resources/fixtures/Blizzard-Lighting-StormChaser.qxf
Was almost perfect.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9199
=> New fixture - Blizzard-Lighting-StormChaser

resources/fixtures/Showtec-Explorer-250-Pro-MKII.qxf
Added gobos and physical data.
Original post:
http://www.qlcplus.org/forum/viewtopic.php?f=5&t=9203
Manual: Google:
showtec explorer 250 pro mkii manual
=> New fixture - Showtec-Explorer-250-Pro-MKII

resources/fixtures/Showtec-Pixel-Bar-12.qxf
Fixture had only one mode and no physical data.
Original post:
http://www.qlcplus.org/forum/viewtopic.php?f=5&t=9203
Manual:
http://www.thomann.de/gb/showtec_pixel_bar_12.htm
=> New fixture - Showtec-Pixel-Bar-12

resources/fixtures/American-DJ-Nucleus-PRO.qxf
Updated physucal data (only pan & tilt) and click and go colours.
=> Updated fixture - American-DJ-Nucleus-PRO

resources/fixtures/American-DJ-Quad-Scan-LED.qxf
Added pan and tilt information and correct some channel descriptions.
=> American dj quad scan led

fixtureeditor/fixtureeditor_ca_ES.ts, ui/src/qlcplus_ca_ES.ts
Update catalan translation (UI and FixtureEditor)
=> Update catalan translation (UI and FixtureEditor)

resources/fixtures/PSL-Strip-Led-RGB-code-K2014.qxf, resources/fixtures/Philips-Selecon-PLProfile1-MkII.qxf
Corrected 16-bit colour LSB channels and other minor things. The full company name is clarified on page two of the datasheet:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9219
=> Philips selecon pl profile1 mk ii

resources/fixtures/Chauvet-SlimPar-Pro-Tri.qxf
Added: Physical data, click and go colours.
<b>Note:</b>The Dimmer Speed channel is not speed-dial speed as such. If is the dimmer function in use - linear, curve etc.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9222
=> New fixture - Chauvet SlimPar Pro Tri

resources/fixtures/Stairville-MH-100-Beam-36x3-LED.qxf
The author has updated the definition with colours etc. See the post. Can't find an English version of the manual.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9160
=> Updated fixture - Stairville-MH-100-Beam-36x3-LED

resources/fixtures/Chauvet-GigBar-IRC.qxf
There are several user manual versions for this unit. Some call the derby effects 'Kinta', others, 'derby'.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9244
http://www.chauvetlighting.co.uk/gig-bar-irc.html
=> New fixture - Chauvet-GigBar-IRC

resources/fixtures/Ghost-Green-30.qxf, resources/fixtures/KOOLlight-3D-RGB-Laser.qxf, resources/fixtures/Mac-Mah-Mac-FOG-DMX.qxf
* Laser: Ghost Green 30mw
* Laser: Kool Light 3D RGB
* Fog machine: Mac Mah Mac FOG
=> Add fixtures

engine/src/doc.cpp, engine/src/fixture.cpp, engine/test/doc/doc_test.cpp, engine/test/doc/doc_test.h, engine/test/efxfixture/efxfixture_test.cpp, engine/test/efxfixture/efxfixture_test.h, engine/test/fixturegroup/fixturegroup_test.cpp, engine/test/fixturegroup/fixturegroup_test.h, engine/test/rgbmatrix/rgbmatrix_test.cpp, ui/src/addfixture.cpp, ui/src/addfixture.h, ui/src/fixturemanager.cpp, ui/test/addfixture/addfixture_test.cpp, ui/test/monitorfixture/monitorfixture_test.cpp, ui/test/monitorfixture/monitorfixture_test.h
http://qlcplus.org/forum/viewtopic.php?f=5&t=9257
- Fix crash related to shared generic fixture definition
- Fix some crashes related to overlapping channels
=> Addfixture

resources/fixtures/Stellar-Labs-ECO-LED-PAR56.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9292
=> New fixture - Stellar-Labs-ECO-LED-PAR56

resources/fixtures/Pulse-SlimLite-56.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9291
This was a mess. Multiple channels used for one channel and detailed info missing.
=> Fixture update - Pulse-SlimLite-56

resources/fixtures/Chauvet-Colorpalette-II.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9290
Removed a load of additional channels.
=> New fixture - Chauvet-Colorpalette-II

resources/fixtures/Chauvet-COLORado-1-Solo.qxf
Straight forward. The colour temperatures come from ShowExpress profile and my own spreadsheet.
http://www.chauvetprofessional.eu/products/colorado-1-solo/
=> New fixture - Chauvet-COLORado-1-Solo

resources/fixtures/Chauvet-Ovation-FD-165WW.qxf
http://www.chauvetprofessional.eu/products/ovation-fd-165ww/
=> New fixture - Chauvet-Ovation-FD-165WW

resources/fixtures/Chauvet-Rogue-RH1-Hybrid.qxf
http://www.chauvetprofessional.eu/products/rogue-rh1-hybrid/
=> New fixture - Chauvet-Rogue-RH1-Hybrid

resources/fixtures/Chauvet-COLORdash-Par-Hex-12.qxf
http://www.chauvetprofessional.eu/products/colordash-par-hex-12/
=> New fixture - Chauvet-COLORdash-Par-Hex-12

resources/fixtures/Eurolite-LED-CLS-9-QCL-RGBW-9x8W-12.qxf
Manual is bottom left of the page.
http://www.thomann.de/gb/eurolite_led_cls_9_qcl_rgbw_9x8w_12.htm
=> New fixture - Eurolite-LED-CLS-9-QCL-RGBW-9x8W-12

resources/inputprofiles/Behringer-BCR2000.qxi
=> added input profile for behringer bcr2000

resources/fixtures/JB-Lighting-A12-Tunable-White.qxf
This fixture comes under LED WASH:
http://www.jblighting.com/
=> Jb lighting a12 tunable white

resources/fixtures/Chauvet-Vue-1.1.qxf
Simple one.
http://www.chauvetlighting.com/vue1-1.html
=> New fixture - Chauvet-Vue-1

resources/fixtures/Coemar-Par-Lite-LED-RGB.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9306
=> New fixture - Coemar-Par-Lite-LED-RGB

resources/fixtures/Chauvet-LED-PAR-64-Tri-C.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9305
Manual from google:
chauvet led par 64 tri c
=> New fixture - Chauvet-LED-PAR-64-Tri-C

resources/fixtures/American-DJ-VBar.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9337
Removed 'Pak' references and altered physical data to suit. Added click and go colours and fixed strobe modes.
=> New fixture - American-DJ-VBar

resources/fixtures/Sagitter-Slimpar-18-RGB.qxf
Edited physical data and changed 7 channel color macro mode as it's different from 1 channel mode.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9362
=> New fixture - Sagitter-Slimpar-18-RGB

resources/fixtures/Microh-LED-Tri-Bar.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9352
=> New fixture - Microh-LED-Tri-Bar

resources/fixtures/American-DJ-12P-Hex.qxf
Added/corrected physical data and more accurate click and go colours.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9338
=> New fixture - American-DJ-12P-Hex

resources/fixtures/JB-Lighting-JBLED-A7.qxf
Here's a translation of the definition. There is an English version at the last part of the manual here:
Google: jb lighting a7 manual
=> New fixture - JB-Lighting-JBLED-A7

resources/fixtures/Chauvet-Intimidator-Spot-100-IRC.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9385
=> New fixture - Chauvet-Intimidator-Spot-100-IRC

resources/fixtures/Chauvet-Abyss-USB.qxf
Simple new 3-channel effect from Chauvet.
http://www.chauvetlighting.eu/abyss-usb.html
=> New fixture - Chauvet-Abyss-USB

resources/fixtures/Chauvet-COREpar-40-USB.qxf
Almost identical to COREpar 80
http://www.chauvetlighting.eu/corepar-40-usb.html
=> New fixture - Chauvet-COREpar-40-USB

resources/fixtures/Chauvet-COREpar-80-USB.qxf
Same as COREpar 80
http://www.chauvetlighting.eu/corepar-80-usb.html
=> New fixture - Chauvet-COREpar-80-USB

resources/fixtures/Chauvet-COREpar-UV-USB.qxf
Single colour variant of the other COREpar series:
http://www.chauvetlighting.eu/corepar-uv-usb.html
=> New fixture - Chauvet-COREpar-UV-USB

resources/fixtures/Chauvet-Intimidator-Scan-305-IRC.qxf
Two new products with the same manual and (almost) the same definition:
http://www.chauvetlighting.eu/intimidator-barrel-305-irc.html
=> New fixture - Chauvet-Intimidator-Scan-305-IRC

resources/fixtures/Chauvet-Intimidator-Barrel-305-IRC.qxf
Slightly different tilt and physical data to the Scan version.
http://www.chauvetlighting.eu/intimidator-barrel-305-irc.html
=> New fixture - Chauvet-Intimidator-Barrel-305-IRC

resources/fixtures/Stairville-DJ-Lase-25+25-G-MK-II.qxf
Added physical data and cleaned up the channel groups a bit.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9420
=> New fixture - Stairville-DJ-Lase-25+25-G-MK-II

resources/fixtures/Chauvet-SlimPAR-T6-USB.qxf
Bog standard fixture.
http://www.chauvetlighting.co.uk/slimpar-t6-usb.html
=> New fixture - Chauvet-SlimPAR-T6-USB

resources/fixtures/Chauvet-SlimBANK-TRI-18.qxf
Straightforward LED fixture.
Stick this in google for the datasheet:
Chauvet SlimBANK TRI-18
=> New fixture - Chauvet-SlimBANK-TRI-18

resources/fixtures/Futurelight-DJ-Scan-600.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9443
Full manual available from Google but doesn't give all physical data as usual. Lumens comes from the actual bulb data, not the fixture.
=> New fixture - Futurelight-DJ-Scan-600

resources/fixtures/Varytec-LED-Pad-7-BA-D.qxf
See attachements for data:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9458
=> New fixture - Varytec-LED-Pad-7-BA-D

resources/fixtures/American-Dj-X-Scan-LED-Plus.qxf
More German needing translation:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9459
http://www.adj.com/x-scan-led-plus
=> New fixture - American-DJ-X-Scan-LED-Plus

resources/fixtures/Involight-LED-CC60S.qxf
This fixture is very similar to the Chauvet models but NOT identical, according to the manuals, so there could be software changes. Value ranges and directions change for channels like prism, focus and gobo rotation.
The DMX part of the manual is in English.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9424&p=41628#p41628
=> New fixture - Involight-LED-CC60S

resources/fixtures/Showtec-Blade-Runner.qxf
Renamed all channels, converted colours to English, added absent physical data, FFS.
Datasheet found with google (first entry found).
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9466
=> New fixture - Showtec-Blade-Runner

resources/fixtures/SGM-G-Profile.qxf
Original request - see my comments on this big fixture:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9345&p=41651#p41651
User manual and physical data (at bottom of page) here:
http://sgmlight.com/products/g-profile/c-23/p-228
=> New fixture - SGM-G-Profile

resources/fixtures/Stairville-MH-x200-Pro-Spot.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9479
=> New fixture - Stairville-MH-x200-Pro-Spot

resources/fixtures/PR-Lighting-XR-230-Spot.qxf
See my comments here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9483
=> New fixture - PR-Lighting-XR-230-Spot

resources/fixtures/PR-Lighting-XLED-1037.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9484
=> New fixture - PR-Lighting-XLED-1037

resources/fixtures/Eurolite-LED-PAR-64-RGBW+UV.qxf
Dead simple:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9485
=> New fixture - Eurolite-LED-PAR-64-RGBW

resources/fixtures/Varytec-LED-Giga-bar-4-MKII.qxf
Standard bar.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9487
=> New fixture - Varytec-LED-Giga-Bar-4-MKII

debian/changelog, engine/src/function.cpp, engine/test/function/function_test.cpp, ui/src/speeddial.cpp, ui/src/virtualconsole/vcspeeddialproperties.cpp
- Fix #723 
- Allow a precision of 1ms instead of 10ms
=> ms precision

plugins/artnet/src/artnetcontroller.cpp, plugins/artnet/src/configureartnet.cpp
=> ArtNet plugin: save full IP addresses

resources/fixtures/Chauvet-Mayhem.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9523
=> New fixture - Chauvet-Mayhem

resources/fixtures/Eurolite-LED-KLS-Laser-Bar-FX-Light-Set.qxf
Original post:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9498#p41725
Google this for the manual (the link doesn't work):
Eurolite LED KLS LASER BAR FX Light Set manual
=> New fixture - Eurolite-LED-KLS-Laser-Bar-FX-Light-Set

plugins/artnet/src/artnetcontroller.cpp, plugins/artnet/src/artnetcontroller.h, plugins/artnet/src/artnetplugin.cpp
artnet info message is changed instead
Should fix #794
=> artnet: dont show popup on bind fail

resources/fixtures/Chauvet-COLORdash-Accent-Quad.qxf
Manual here:
http://www.chauvetprofessional.com/products/colordash-accent-quad/
=> New fixture - Chauvet-COLORdash-Accent-Quad

resources/fixtures/American-DJ-Jellydome.qxf
I've renamed it as a moonflower effect. *shrugs*
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9564
=> New fixture - American-DJ-Jellydome

plugins/artnet/src/ArtNet_ca_ES.ts
Catalan translation Artnet plugin new strings
=> Catalan translation Artnet plugin new strings

resources/fixtures/Ayra-TDC-Agaricus.qxf
http://www.bax-shop.nl/led-lichteffect/ayra-tdc-agaricus-led-lichteffect
=> Fixture Ayra-TDC-Agaricus

resources/fixtures/American-DJ-Pinspot-LED-Quad-DMX.qxf
Original post:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9611
No physical data, foreign spelling, block capitals and missing strobe functions fixed.
=> New fixture - American-DJ-Pinspot-LED-Quad-DMX

resources/fixtures/Briteq-LDP-Powerbar-12TC.qxf
Fixed typos and added/fixed channels to reflect the manual.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9618
=> New fixture - Briteq-LDP-Powerbar-12TC

resources/fixtures/Briteq-LDP-Powerbar-6TC.qxf
Same as the 12TC but with different physical properties.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9618
=> New fixture - Briteq-LDP-Powerbar-6TC

resources/fixtures/Stairville-AF-180-LED-Fogger-Co2-FX.qxf
No changes required from the original! :+1: 
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9610
=> New fixture - Stairville-AF-180-LED-Fogger-Co2-FX

resources/fixtures/American-DJ-Stinger-II.qxf
=> New fixture - American-DJ-Stinger-II

resources/rgbscripts/rgbscripts.pro, resources/rgbscripts/strobe.js
This rgbscript will turn all the fixtures in a fixture group on and off.
=> Strobe rgbscript

webaccess/res/keypad.html
Added comments to keypad.html code. I hope that I explained this code clearly. ;-)
=> Added comments to keypad.html code

resources/fixtures/American-DJ-Mega-QA-Par38.qxf
Typos fixed etc, etc.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9662
=> New fixture - American-DJ-Mega-QA-Par38

resources/fixtures/Martin-MAC-250-Wash.qxf
I had to convert this to English.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9632
Manual:
http://www.martin.com/Martin.Download.aspx?file=/files/files/productdocuments/11_MANUALS/999/UM_MAC250Wash_EN_G.pdf
=> New fixture - Martin-MAC-250-Wash

resources/fixtures/Starway-MaxKolor-18.qxf
Minor changes:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9634&p=42497#p42497
The physical data has been fixed but there still errors so I have modified it futher:
8 bit, 9-channel mode missing.
Incorrect power consumption.
Strobe does macro speed too.
=> Fixture update - Starway-MaxKolor-18

resources/fixtures/Stairville-MH-X60th-LED-Spot.qxf
I looked through the gobos 15 times but could not see 'Clay Paky/gobo0067.png'.
=> Fixture update: Original author found better gobo image for gobo 2.

resources/fixtures/Luxibel-LX161.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9650
=> New fixture - Luxibel-LX161

resources/fixtures/Cameo-CLHB400RGBW.qxf
I have no idea what the OP was thinking here. The 12:20pm post is complete jibberish.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9715
=> New fixture - Cameo-CLHB400RGBW

ui/src/virtualconsole/vcxypadfixture.cpp, ui/test/vcxypadfixture/vcxypadfixture_test.cpp, ui/test/vcxypadfixture/vcxypadfixture_test.h
This is the package that **should** compile with travis-ci.  It contains the modified test .cpp with latest corrections along with the **"should be"** fixed vcxypadfixture.cpp giving the intended results.
=> XYPad reverse test with fix

resources/fixtures/FixturesMap.xml, resources/fixtures/Showlite-Flood-Light-Panel-144x10mm-LED-RGBW.qxf
Manual: http://www.kirstein.de/docs/manuals/sl-flp144rgbw-dten-0515.pdf
=> New fixture - Showlite Flood Light Panel 144x10mm LED RGBW

resources/fixtures/Color-Imagination-LedSpot-90-(SI-052).qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9906
Fixture was not quite complete. Datasheet is a meagre 46MB pdf file linked to above.
=> New fixture - Color-Imagination-LedSpot-90-SI-052

resources/fixtures/Robe-Spot-575-XT.qxf
OK. Some missing physical data and incomplete capabilities.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9907
=> New fixture - Robe-Spot-575-XT

resources/fixtures/Chauvet-Mini-Kinta.qxf, resources/fixtures/Robe-Spot-575-XT.qxf
Corrected channel type and added some colours. Datasheet here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9636
=> Chauvet mini kinta

resources/fixtures/Eurolite-LED-ML-56-QCL-RGBW-RGBA-18x8W.qxf
Simple fixture with a quirk.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9901
=> New fixture - Eurolite-LED-ML-56-QCL-RGBW-RGBA-18x8W

resources/fixtures/High-End-Systems-TechnoSpot.qxf
There were about 6 capital letters in the whole definition:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9767
The gobo pics are approximate.
=> New fixture - High-End-Systems-TechnoSpot

resources/fixtures/American-DJ-Inno-Pocket-Spot-Twins.qxf
Original post/datasheet:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10019
This definition was about 30% complete and required every channel modifying or creating.
=> New fixture - American-DJ-Inno-Pocket-Spot-Twins

resources/fixtures/American-DJ-Fog-Fury-3000-WiFly.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10018
Nice and simple.
=> New fixture - American-DJ-Fog-Fury-3000-WiFly

resources/fixtures/American-DJ-Event-Bar-Pro.qxf
I missed the master dimmer from the heads first time round.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10017
=> American dj event bar pro

ui/src/qlcplus_ca_ES.ts
=> Catalan Translation

ui/src/qlcplus_de_DE.ts
=> Update german translation

resources/fixtures/Pro-Lights-LumiPIX-12Q.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10044
=> New fixture - Pro-Lights-LumiPIX-12Q

resources/fixtures/Stairville-DCL-Flat-Par-18x4W-CW-WW.qxf
Not sure of the use of amber for warm white, but...
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9958
=> New fixture - Stairville-DCL-Flat-Par-18x4W-CW-WW

resources/fixtures/iSolution-iColor-4.qxf
Hi,
Is it possible to add this fixture to the main ? I test it with the product.
If you think I need to modify something, please let me know.
Thanks
=> Adding iSolution iColor4 fixture

resources/fixtures/ETC-ColorSource-Spot.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=10009
Physical and photometric data is from the ETC website (I have used maximum values).
=> New fixture - ETC-ColorSource-Spot

resources/fixtures/Cameo-LED-MultiPAR-CLM-PAR-COB1.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9957
=> New fixture - Cameo-LED-MultiPAR-CLM-PAR-COB1

resources/fixtures/American-DJ-Chameleon-QBar-Pro.qxf
Datasheet here:
[http://www.adj.com/chameleon-qbar-pro](url)
Lots and lots and lots of colour macros.
=> New fixture - American-DJ-Chameleon-QBar-Pro

resources/fixtures/American-DJ-Vizi-Beam-RXONE.qxf
http://www.americandj.eu/en/vizi-beam-1rx.html
=> New fixture - American-DJ-Vizi-Beam-RXONE

resources/fixtures/JB-Lighting-Varyscan-P6.qxf
Spent over 1 hour adding capital letters/correcting spelling and generally fixing:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10081
There are conflicting images of the gobos so I've left them blank. Besides, they're changeable.
=> New fixture - JB-Lighting-Varyscan-P6

resources/fixtures/Proel-PLLEDMLBG.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10144
The creator has added an 8-channel, 8-bit mode not mentioned in the manual. I left it in.
=> New fixture - Proel-PLLEDMLBG

resources/fixtures/Chauvet-RotoSphere-LED.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10159
A few typos fixed and physical data added from an online version of the manual.
=> New fixture - Chauvet-RotoSphere-LED

resources/fixtures/Briteq-Spectra-3D-Laser.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=10184
=> New Fixture - Briteq-Spectra-3D-Laser

resources/fixtures/Martin-MH2-Wash.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10189
=> New fixture - Martin-MH2-Wash

engine/src/qlcchannel.cpp, engine/src/qlcchannel.h, engine/test/qlcchannel/qlcchannel_test.cpp, ui/src/clickandgowidget.cpp, ui/src/clickandgowidget.h, ui/src/consolechannel.cpp, ui/src/virtualconsole/vcsliderproperties.cpp
While working with the Source Four LED lustr from ETC I wrote the fixture, which I will add to the forum later. Since it has Indigo as LED color, I added the possibility to choose it in the fixture creator.
=> Adds Indigo as additional channel color

platforms/linux/qlcplus-fixtureeditor.desktop, platforms/linux/qlcplus.desktop
=> French integration improvements

resources/fixtures/American-DJ-Flat-Par-Tri7X.qxf
Added colour macros, photometric data and general bits.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10304
Google for the datasheet.
=> New fixture - American-DJ-Flat-Par-Tri7X

resources/fixtures/Blizzard-Lighting-LB-Par-Hex.qxf
Request:
[http://www.qlcplus.org/forum/viewtopic.php?f=6&t=10303&p=44737#p44737](url)
Datasheet:
[http://www.blizzardlighting.com/products/par-cans-and-wash-lights/item/363-lbpar-hex](url)
Absolutely no idea how channel 11 works so just copied it.
=> New fixture - Blizzard-Lighting-LB-Par-Hex

resources/fixtures/Ledj-Stage-Color-24.qxf
Post here:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10353
=> New fixture - Ledj-Stage-Color-24

resources/fixtures/Ledj-59-7Q5-RGBW.qxf
Original post:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10352
=> New fixture - Ledj-59-7Q5-RGBW

resources/fixtures/Ledj-59-7Q5-RGBA.qxf
Slight change from white to amber.
=> New fixture - Ledj-59-7Q5-RGBA

resources/fixtures/Ledj-58-7Q5-RGBW.qxf
Lower power version of the 59-7Q5 so physical data updated
=> New fixture - Ledj-58-7Q5-RGBW

resources/fixtures/American-DJ-Inno-Spot-Elite.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10356
=> New fixture - American-DJ-Inno-Spot-Elite

resources/fixtures/American-DJ-Stinger.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10346
=> New fixture - American-DJ-Stinger

resources/fixtures/Blizzard-Lighting-Rocklite-RGBAW.qxf
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10358
See specs bottom of page 17:
Coolness Factor: Leventy Billion Percent
=> New fixture - Blizzard-Lighting-Rocklite-RGBAW

resources/fixtures/Showtec-Phantom-95-LED-Spot.qxf
Hardly any changes apart from slow to fast backwards and wrong lumens data (lux).
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=10342
=> New fixture - Showtec-Phantom-95-LED-Spot

resources/fixtures/American-DJ-XS-600.qxf
http://www.americandj.eu/en/xs-600.html
=> New fixture - American-DJ-XS-600

resources/fixtures/High-End-Systems-Studio-Beam.qxf
Had to reclone to add this... Things got a bit screwed up.
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=10351&start=10
=> New fixture - High-End-Systems-Studio-Beam

resources/fixtures/American-DJ-Comscan-LED.qxf, resources/fixtures/High-End-Systems-Studio-Beam.qxf
Originator:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=5789
Datasheet:
http://www.americandj.eu/en/comscan-led.html
Notes:
No brightness data, gobo colours taken from original definition.
=> American dj comscan led

resources/fixtures/Stairville-LED-Flood-Panel-150.qxf
Update request to swap physical dimensions as reported a user:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=10387
=> Updated fixture - Stairville-LED-Flood-Panel-150

resources/fixtures/Eurolite-TMH-10.qxf
http://www.culture-live.de/docs/anleitungen/manual/Eurolite%20TMH.10.pdf
=> added Eurolite-TMH-10

plugins/gpio/gpioconfiguration.cpp, plugins/gpio/gpioplugin.cpp
m_enabled was not initialized causing some pins to never get
set as exported
=> uninitialized variable in GPIO plugin

resources/fixtures/American-DJ-FREQ-16-Strobe.qxf, resources/fixtures/American-DJ-FREQ-5-Strobe.qxf
Corrected the type of the "ADJ FREQ 16" and added the "ADJ FREQ 5" as a new fixture.
=> New fixture and a small fix

plugins/midi/MIDI_de_DE.ts, ui/src/qlcplus_de_DE.ts
Two things where a bit wrong, the others are additions.
=> Updated german translation

ui/src/virtualconsole/vccuelist.cpp
cosmetic change to make these two buttons look a bit tidier
=> left-align blend and link buttons in vccuelist's xfade section

ui/src/virtualconsole/vccuelist.cpp, ui/src/virtualconsole/vccuelist.h
=> VCCuelist: Set Crossfader top labels to fixed width, honouring current font metrics

ui/src/virtualconsole/vcwidget.cpp
This should fix #940 
I have no external controller at hand atm and don't work with input profiles so much so somebody should test if this breaks something else beforehand.
=> Fixed input profiles not honored on other page than 1

ui/src/virtualconsole/vcframe.cpp
This fixes a crash when trying to copy a multipage frame as reported here: http://www.qlcplus.org/forum/posting.php?mode=reply&f=33&t=10948
=> VC/Frame: Fixed crash when copying multipage frame

engine/audio/src/audio.cpp, engine/audio/src/audio.h, engine/audio/src/audiorenderer.cpp, engine/audio/src/audiorenderer.h, qmlui/audioeditor.cpp, qmlui/audioeditor.h, resources/docs/audioeditor.html, ui/src/audioeditor.cpp, ui/src/audioeditor.h, ui/src/audioeditor.ui
I needed support for perfectly looped audio samples being played in infinite loop until explicitly stopped, so I created it. Someone else might find it useful.
=> Looped audio

resources/miditemplates/APC40MK2.qxm
- has correct init string for Mode 2
=> adding support for APC 40 MK II

ui/src/qlcplus_ca_ES.ts
Updated catalan translation 5 new in UI
Fixed some translation errors
=> Updated catalan translation 5 new in UI

ui/src/qlcplus_ca_ES.ts
Updated catalan translation (5 new in UI)
=> Updated catalan translation (5 new in UI)

ui/src/qlcplus_ca_ES.ts, webaccess/src/webaccess_ca_ES.ts
Catalan translation update (4 new in ui)
Catalane translation update (20 new in web access)
=> Catalan translation updates 4 new in ui, 20 new in web access

resources/fixtures/Eurolite-LED-FE-1500.qxf
Added missing channel to the Eurolite LED FE 1500.
=> Fixture: Added 9th channel (rotation of lasers) to the Eurolite-LED-FE-1500

debian/control, debian/copyright
- description fields : remove unnecessary spaces
- lists : one items per line (easier to read quickly, closer to the debian-multimedia team guidelines/habits)
- lists : ordered alphabetically (same than above)
=> debian packaging update

ui/src/qlcplus_ca_ES.ts
Updated catalan translation (6 new in UI)
Fixed some typo
=> Updated catalan translation (6 new in UI)

webaccess/src/webaccess_ja_JP.ts
=> translate jp new in webaccess

ui/src/qlcplus_ja_JP.ts
=> Update Japanese Translation 

.travis.yml, resources/fixtures/JB-Lighting-Varyscan-2.qxf, resources/fixtures/Lite-Works-ColorChanger.qxf, resources/fixtures/Sagitter-Miniscan-2001.qxf, resources/fixtures/check, resources/fixtures/scripts/check, resources/fixtures/scripts/check.bat, unittest.sh
- add fixture checking to travis
- fix invalid fixtures so that now all fixture validate against XML schema
=> Fixture validation

plugins/hid/HID_fr_FR.ts, ui/src/qlcplus_fr_FR.ts, webaccess/src/webaccess_fr_FR.ts
And corrected two others in ui/src/qlcplus_fr_FR.ts and plugins/hid/HID_fr_FR.ts
=> Added translations in webaccess_fr_FR.ts

qmlui/qlcplus_ca_ES.ts, qmlui/qmlui.pro
=> qmlui: Catalan translation

qmlui/qml/fixturesfunctions/3DView/SpotlightConeEntity.qml, qmlui/qml/fixturesfunctions/3DView/shaders/spotlight_scattering.frag, qmlui/qml/fixturesfunctions/3DView/shaders/spotlight_shading.frag
qmlui: expose the goboRotation to the shaders.
=> qmlui: expose the goboRotation to the shaders.

qmlui/mainview3d.cpp, qmlui/qml/fixturesfunctions/3DView/DirectionalLightFilter.qml, qmlui/qml/fixturesfunctions/3DView/GBuffer.qml, qmlui/qml/fixturesfunctions/3DView/SelectionEntity.qml, qmlui/qml/fixturesfunctions/3DView/SpotlightConeEntity.qml, qmlui/qml/fixturesfunctions/3DView/StageBox.qml, qmlui/qml/fixturesfunctions/3DView/StageRock.qml, qmlui/qml/fixturesfunctions/3DView/StageSimple.qml, qmlui/qml/fixturesfunctions/3DView/StageTheatre.qml, qmlui/qml/fixturesfunctions/3DView/shaders/directional.frag, qmlui/qml/fixturesfunctions/3DView/shaders/geo.frag
Add support for specular shading in the rendering engine.
=>  Add support for specular shading in the rendering engine.

qmlui/mainview3d.cpp, qmlui/qml/fixturesfunctions/3DView/StageRock.qml
qmlui: fix rendering for objects without a material.
=> qmlui: fix rendering for objects without a material.

qmlui/qml/popup/PopupNetworkConnect.qml
Found during translation: I'm not sure what is meant there but the current string sounded a bit odd
=> Improve one UI string

qmlui/qlcplus_de_DE.ts
#1096 wasn't up-to-date with latest master so here we go :)
=> Update german translations from current master

qmlui/qml/fixturesfunctions/3DView/RenderShadowMapFilter.qml, qmlui/qml/fixturesfunctions/3DView/SpotlightConeEntity.qml
performance optimizations for zero-intensity lights.
=> performance optimizations for zero-intensity lights.

qmlui/qlcplus_ca_ES.ts
Updated new and modified strings in catalan translation.
=> Updated qmlui catalan translation

fixtureeditor/fixtureeditor_cz_CZ.ts, fixtureeditor/fixtureeditor_de_DE.ts, fixtureeditor/fixtureeditor_es_ES.ts, fixtureeditor/fixtureeditor_fr_FR.ts, fixtureeditor/fixtureeditor_it_IT.ts, fixtureeditor/fixtureeditor_nl_NL.ts, plugins/udmx/src/uDMX_cz_CZ.ts, plugins/udmx/src/uDMX_fr_FR.ts, qmlui/qlcplus_es_ES.ts, qmlui/qlcplus_it_IT.ts, ui/src/qlcplus_cz_CZ.ts, ui/src/qlcplus_de_DE.ts, ui/src/qlcplus_es_ES.ts, ui/src/qlcplus_fr_FR.ts, ui/src/qlcplus_it_IT.ts, ui/src/qlcplus_nl_NL.ts
=> Correct spaces before punctuation in translations

qmlui/qlcplus_de_DE.ts
I messed up my fork, so #1099 was closed automatically. Here it is again.
Please review @fxedel and/or @kripton.
=> Improve German translations

qmlui/contextmanager.cpp, qmlui/mainview3d.cpp, qmlui/mainview3d.h
the point-picking feature now works for arbitrarily rotated fixtures.
=> Arbitrary rotation point picking

plugins/dmxusb/src/DMX_USB_ca_ES.ts
Catalan translation, updated new strings DMX-USB Plugin
=> Update DMX-USB Plugin Catalan translation

resources/fixtures/Varytec/Varytec-Street-Bar.qxf
https://www.thomann.de/gb/varytec_led_street_bar_16x3w_rgb_ip65.htm
=> Additional Fixture: Varytec Street Bar

fixtureeditor/fixtureeditor_fr_FR.ts, plugins/dmxusb/src/DMX_USB_fr_FR.ts, plugins/midi/src/MIDI_fr_FR.ts, plugins/osc/OSC_fr_FR.ts, plugins/udmx/src/uDMX_fr_FR.ts, qmlui/qlcplus_fr_FR.ts, ui/src/qlcplus_fr_FR.ts, webaccess/src/webaccess_fr_FR.ts
Add French translation for the new 4.12.0 and 5alpha4 updates. (A bit late, but finally, here they are)
@jeromelebleu
=> Add French translation for new updates

resources/fixtures/Martin/Martin-MAC250-Krypton.qxf
Feel free to leave comments if you think some feature would have been more appropriate.
[Datasheet for the fixture](https://github.com/mcallegari/qlcplus/files/2657629/UM_MAC250Kr_EN_A.pdf)
=> Updated fixture Martin MAC250 Krypton

debian/changelog, engine/src/qlcinputprofile.cpp, engine/src/qlcinputprofile.h, platforms/linux/qlcplus.spec, plugins/os2l/org.qlcplus.QLCPlus.os2l.metainfo.xml, plugins/os2l/os2l.pro, plugins/os2l/os2lconfiguration.cpp, plugins/os2l/os2lconfiguration.h, plugins/os2l/os2lconfiguration.ui, plugins/os2l/os2lplugin.cpp, plugins/os2l/os2lplugin.h, plugins/plugins.pro, resources/docs/html_en_EN/index.html, resources/docs/html_en_EN/index_pdf.html, resources/docs/html_en_EN/os2lplugin.html, resources/docs/html_ja_JP/index.html, resources/docs/html_ja_JP/index_pdf.html, resources/docs/html_ja_JP/os2lplugin.html, ui/src/inputchanneleditor.cpp, ui/src/inputprofileeditor.cpp
Preliminary implementation of OS2L communication
=> plugins: new OS2L plugin

resources/rgbscripts/strobe.js
a small improvement for strobe.js to set a frequency for the strobe. with this you cannot only blink every second step. you can define "blink on every Xth step". Also changed the big if-else-block to a simple one-liner
=> Rgbscripts strobe

plugins/dmxusb/src/dmxusbopenrx.cpp
A really important fix reported by lintian! :)
=> plugins/dmxusb: fix spelling error

resources/rgbscripts/devtool.html, resources/rgbscripts/devtool.js
* Properly support primary and secondary colors (and hide input fields, depending on `algo.acceptColors`)
* Fixed issue when "Start test" has been clicked multiple times
* Fixed missing `#` in `cell.style.backgroundColor` which lead to sometimes uncolered cells
* Add title to cells so you can easily check a specific cell's position and color
* Use modern HTML form element features (like input type number, min/max)
* Refactor JS logic, e.g. by using global variables instead of always reading input element values
I'm also thinking about adding support for API version 2 parameters – do you want to wait for this first or should I open a new PR then?
=> Improve RGB scripts devtool

create-deb.sh, debian/rules
=> compile debian package with all CPUs

qmlui/qml/virtualconsole/VCWidgetItem.qml
Forum thread: https://www.qlcplus.org/forum/viewtopic.php?f=35&t=14140
=> preserve aspect ratio of background image in virtual console

plugins/dmxusb/src/DMX_USB_ca_ES.ts, plugins/dmxusb/src/DMX_USB_es_ES.ts, plugins/os2l/OS2L_ca_ES.ts, plugins/os2l/OS2L_es_ES.ts, qmlui/qlcplus_ca_ES.ts, qmlui/qlcplus_es_ES.ts, ui/src/qlcplus_ca_ES.ts, ui/src/qlcplus_es_ES.ts
Updated Catalan and Spanish translations
=> Updated Catalan and Spanish translations

resources/fixtures/Pro-Lights/Pro-Lights-Fury-FY250S.qxf, resources/fixtures/Pro-Lights/Pro-Lights-Fury-FY250W.qxf, resources/fixtures/Pro-Lights/Pro-Lights-Genesis.qxf, resources/fixtures/Pro-Lights/Pro-Lights-GoboMix.qxf, resources/fixtures/Pro-Lights/Pro-Lights-LumiPAR18QPRO.qxf, resources/fixtures/Pro-Lights/Pro-Lights-LumiPAR18QTour.qxf, resources/fixtures/Pro-Lights/Pro-Lights-LumiPIX-12Q.qxf, resources/fixtures/Pro-Lights/Pro-Lights-LumiPar-18-Tri.qxf, resources/fixtures/Pro-Lights/Pro-Lights-LumiPar-7QPro.qxf, resources/fixtures/Pro-Lights/Pro-Lights-Miniruby.qxf, resources/fixtures/Pro-Lights/Pro-Lights-Moonstone.qxf, resources/fixtures/Pro-Lights/Pro-Lights-Onyx.qxf, resources/fixtures/Pro-Lights/Pro-Lights-PIXIEWASH.qxf, resources/fixtures/Pro-Lights/Pro-Lights-SmartBat.qxf, resources/fixtures/Pro-Lights/Pro-Lights-SmartBatHEX.qxf
Added presets for capability in maintenance and gobo groups in some lamps.
We have improved our review process and our git management. This is a small pull request to check if the improvements have been effective.
=> Maintenance presets

resources/fixtures/American_DJ/American-DJ-X-Scan-LED-Plus.qxf, resources/fixtures/Briteq/Briteq-BT-W07L12.qxf, resources/fixtures/Eurolite/Eurolite-TSL-200.qxf, resources/fixtures/Martin/Martin-MAC-101.qxf, resources/fixtures/Martin/Martin-MAC-Aura.qxf, resources/fixtures/Martin/Martin-MAC-Quantum-Profile.qxf, resources/fixtures/Martin/Martin-MAC250-Entour.qxf, resources/fixtures/Martin/Martin-MH2-Wash.qxf, resources/fixtures/Martin/Martin-MX-10.qxf, resources/fixtures/Martin/Martin-MiniMAC-Maestro.qxf
The last part of fixtures with changed maintenance presets. As you wished I filtered out all fixtures with SmallToBig preset changed.
=> Update maintenane presets. Fixtures with SmallToBig preset changed.

resources/rgbscripts/devtool.html, resources/rgbscripts/devtool.js
I updated the RGBscripts devtools to support the API v2 parameters and support the script developer in different ways:
- Add display of parameters from API v2
- Use local storage to let parameters survive a reload after a script update
- Update event handling to update matrix updates when changing e.g. speed
- Start timer on reload to make debugging more efficient
- Update visual appearance to let matrix better visible
- make HTML file more conforming to HTML standards to suppress systematic error messages and improve debugging of scripts
May this be useful to the project.
Hans-Jürgen
=> Add APIv2 support to RGBscript devtool.html

resources/rgbscripts/devtool.html, resources/rgbscripts/devtool.js
Improvements and some error corrections:
- Clear the table of properties when loading a new algorithm before the APIv2 check
- Use DOM objects rather than writing the innerHTML directly.
- Define variables in their block scope
=> devtool.js coding corrections

resources/rgbscripts/alternate.js
Implement code fixes as indicated by Codacy.
=> Codacy derived fixes to alternate.js

resources/fixtures/Varytec/Varytec-Giga-Bar-Pix-8-RGB.qxf
Ref Manual: https://images.static-thomann.de/pics/atg/atgdata/document/manual/c_460683_460684_r1_en_online_2.pdf
=> Add Fixture Varytec-Giga-Bar-Pix-8-RGB

resources/rgbscripts/starfield.js
- adding brightness inversion
- updating attribution
=> Updated starfield.js

resources/rgbscripts/circles.js
- added size
- added pulse fade mode
- added fill
- updated attribution
=> Updated Circles.js

resources/rgbscripts/rgbscripts.pro
Forgot to add this when I made the initial commit of lines.js.
=> adding lines.js to rgbscripts.pro for install management.

resources/rgbscripts/rgbscripts.pro, resources/rgbscripts/snowbubbles.js
This RGB script displays either pixels falling or rising in different Z-levels and intensity. The effect can simulate falling snow or bubbles (e.g. in combination with the ocean effect)
it supports flakes in random colors and can be configured to apply a random windchill which moves the pixel flakes / bubbles to simulate wind gusts (or water waves respectively).
I hope this may this be useful in themes around winter and water.
=> Display snow flakes falling or air bubbles rising.

resources/fixtures/Briteq/Briteq-BTX-Saturn-270W.qxf, resources/fixtures/Chauvet/Chauvet-Maverick-MK3-Profile-CX.qxf, resources/fixtures/Coemar/Coemar-LEDko-FullSpectrum-6.qxf, resources/fixtures/Elation/Elation-Proteus-Hybrid.qxf, resources/fixtures/Eurolite/Eurolite-LED-TMH-X10.qxf, resources/fixtures/Futurelight/Futurelight-EYE-7-i.qxf
Added fixtures: 
- Briteq BTX Saturn 270W, 
- Chauvet Maverick MK3 Profile-CX, 
- Coemar LEDko FullSpectrum 6, 
- Elation Proteus Hybrid, 
- Eurolite LED TMH X10, 
- Futurelight EYE 7 i
=> Added new fixtures: Briteq, Chauvet, Coemar, Elation, Eurolite, Futurelight

qmlui/qlcplus_ca_ES.ts, qmlui/qlcplus_es_ES.ts
Updated qmlui catalan and spanish translations
=> Updated qmlui catalan and spanish translations

plugins/peperoni/common/peperonidefs.h, plugins/peperoni/common/unixioenumerator.cpp, plugins/peperoni/unix/peperonidevice.cpp
New Version of Rodin1 MK3 is not found.
=> integrate peperoni Rodin1 mk3 

qmlui/qlcplus_fr_FR.ts
Also ran `lupdate` to translate the fresh strings
=> Add and validate new translations for fr_FR

webaccess/res/keypad.html, webaccess/res/simpledesk.js, webaccess/res/websocket.js
this PR will fix a typo introduced in my previous PR #1327.
=> fix: typo on websocket error handling

engine/src/qlcphysical.cpp, engine/src/scriptv4.cpp, engine/test/rgbscript/rgbscript_test.cpp, fixtureeditor/util.h, ui/src/scripteditor.cpp
Related to https://github.com/mcallegari/qlcplus/issues/1329.
Documentation
https://doc.qt.io/qt-5/qregularexpression.html#introduction
=> Re-Enable CAPS check in fixtureeditor and update other RexExp patterns

resources/rgbscripts/circular.js, resources/rgbscripts/rgbscripts.pro
Hello Massimo,
I was in need for a script to apply some circular effects for a circular light arrangement. So I went to apply some more trigonometric functions to make up some circular effects, such as radar or circles.
Lights can now be arranged in a matrix like the following figure to apply the effects best.
=> Rgbscript circular

engine/test/rgbscript/rgbscript_test.cpp, resources/rgbscripts/rgbscripts.pro
The alternate.js script was missing in the .pro build file. I also extended a test to detect that in the future.
=> Rgbscripts build config

resources/fixtures/Cameo/Cameo-F2-T-PO.qxf, resources/fixtures/FixturesMap.xml
Technical Data Sheet and DMX Control Table are available at
https://www.cameolight.com/en/solutions/rental/static-lighting/theater-lights/20477/f2-t-po
=> Add Cameo F2 T PO fixture

resources/fixtures/FixturesMap.xml, resources/fixtures/Ibiza/Ibiza-PAR-LED-710.qxf
This pull request adds the Ibiza PARLED710 fixture.
=> Add Ibiza/Ibiza-PAR-LED-710.qxf fixture

resources/fixtures/AFX/AFX-Spot-60-LED.qxf, resources/fixtures/FixturesMap.xml
This pull request adds the AFX Spot60LED fixture.
=> Add AFX/AFX-Spot-60-LED.qxf fixture

resources/fixtures/FixturesMap.xml, resources/fixtures/Ghost/Ghost-Venum-12W-RGBW.qxf
This pull request adds the Ghost Venum fixture.
=> Add Ghost/Ghost-Venum-12W-RGBW.qxf

platforms/linux/linux.pro, platforms/linux/qlcplus.spec
The appimage changes are blind and untested
=> Minor linux changes while looking at qml mode

plugins/midi/src/macx/coremidiinputdevice.cpp
This issues fixes issue #1390.
=> Fix concurrent MIDI issue on Mac

resources/fixtures/Equinox/Equinox-Fusion-Spot-MKIII.qxf
Forum post: https://www.qlcplus.org/forum/viewtopic.php?f=3&t=16217
=> Fixture: Equinox Fusion Spot MK III

CMakeLists.txt, coverage_cmake.sh, engine/src/CMakeLists.txt, qmake2cmake.md, unittest_cmake.sh
@mcallegari I think I have done.
Tested on my side for both of QLCv4 and QLCv5.
Please review this PR and give me feedbacks.
=> CMake Coverage build

resources/rgbscripts/circular.js, resources/rgbscripts/devtool/devtool.js
This pull request merges the propellor functionality as proposed in #1434 into the circular.js script, thus:
- Merging center gap into circular.js modes
- Adding a parameter for line width / weight in circular.js
- Adding possibility for multiple blades for the propellor
- Adding possibility to limit the propellor to a circular area
The direction can be set by the direction (forward / reversed) matrix setting
Please review and check the functionality from propellor.js is integrated correctly in circular.js, @yestalgia
=> Rgbscript circular propellor

fixtureeditor/fixtureeditor_ca_ES.ts, fixtureeditor/fixtureeditor_es_ES.ts
Updated catalan and spanish translations in fixtureeditor
=> Updated catalan and spanish translations in fixtureeditor

resources/fixtures/FixturesMap.xml, resources/fixtures/Varytec/Varytec-Hero-Spot-60.qxf
According to user manual at https://images.thomann.de/pics/atg/atgdata/document/manual/449221_c_449221_481679_v3_en_online.pdf
=> Introduce VaryTec Hero Spot 60 fixture

ui/src/virtualconsole/vccuelist.cpp, ui/src/virtualconsole/vccuelist.h, webaccess/res/virtualconsole.css, webaccess/res/virtualconsole.js, webaccess/res/websocket.js, webaccess/src/webaccess.cpp, webaccess/src/webaccess.h
Hi, @mcallegari 
Cue List side fader(none, crossfade, steps) is now supported
Please review it and give me feedbacks.
=> Webaccess cuelist side fader

ui/src/virtualconsole/vccuelist.cpp, ui/src/virtualconsole/vccuelist.h, webaccess/res/virtualconsole.css, webaccess/res/virtualconsole.js, webaccess/res/websocket.js, webaccess/src/webaccess.cpp, webaccess/src/webaccess.h
@mcallegari 
Please review and give feedback.
=> Cue List "Play/Stop + Pause" layout is now supported.

ui/src/virtualconsole/vcmatrix.cpp, ui/src/virtualconsole/vcmatrix.h, webaccess/res/virtualconsole.css, webaccess/res/virtualconsole.js, webaccess/res/websocket.js, webaccess/src/webaccess.cpp, webaccess/src/webaccess.h
@mcallegari 
Hi, the Animation(Matrix) widget is now supported. Please review and give feedback.
Thank you.
=> Animation(Matrix) widget is now supported.

engine/src/efx.cpp, engine/src/efx.h
Added a new EFX algorithm - SquareTrue with 4 points.  This is my 1st attempt to contribute to QLC+ code - I don't know what to do with the unit tests & make test doesn't work on my build environment (windows).  Hope this is of some use ;-)
=> New EFX algorithm - SquareTrue

resources/fixtures/Bright/Bright-XBAR.qxf
Added fixture definition for the Bright XBAR 12 cell RGBAWUV LED bar
=> resources: Add fixture definition for Bright XBAR

ui/src/virtualconsole/vcframe.cpp, ui/src/virtualconsole/vcframe.h, ui/src/virtualconsole/vcmatrix.cpp, ui/src/virtualconsole/vcwidget.cpp, ui/src/virtualconsole/vcwidget.h, webaccess/res/simpledesk.js, webaccess/res/virtualconsole.css, webaccess/res/virtualconsole.js, webaccess/res/websocket.js, webaccess/src/webaccess.cpp, webaccess/src/webaccess.h
@mcallegari 
Hi, the following widgets' enable/disable states are changed when you check/uncheck the frame enable.
VCButton
VCSlider
VCKnob
VCCueList
VCLabel
VCClock
Please review and give feedback.
Thank you.
=> Webaccess frame enable disable v2

ui/src/grandmasterslider.cpp, webaccess/res/virtualconsole.js, webaccess/res/websocket.js, webaccess/src/webaccess.cpp, webaccess/src/webaccess.h
webaccess virtual console grand master is supported.
=> Webaccess virtual console grand master

ui/src/qlcplus_ca_ES.ts, ui/src/qlcplus_es_ES.ts
Updated catalan ans spanish translations
=> Updated catalan ans spanish translations

resources/fixtures/beamZ/beamZ-BAC500.qxf, resources/fixtures/beamZ/beamZ-BAC506.qxf
This PR adds a couple of beamZ fixtures:
=> Add beamZ BAC500 and BAC506 fixtures

resources/fixtures/American_DJ/American-DJ-Par-Z4.qxf, resources/fixtures/OXO/OXO-ColorBeam-7-FCW-IR.qxf, resources/fixtures/Pro-Lights/Pro-Lights-Pixie-Spot.qxf, resources/fixtures/beamZ/beamZ-SB400.qxf
American DJ Par Z4
OXO ColorBeam 7 FCW IR
Pro Lights Pixie Spot
beamZ SB400
=> Add new fixtures

plugins/dmxusb/src/vinceusbdmx512.cpp, plugins/dmxusb/src/vinceusbdmx512.h
The VinceUSBDMX512 plugin is not working anymore in v4.13.0, the interface opening and closing are working but nothing is send to the output. I didn't spent too much time to try to understand why but instead I rewrite some part of it to use threading as the other dmxusb plugins. The output is now working again, there is still the input to code but I don't have required equipment to test.
Any review is welcome since I am not really familiar anymore with C++/Qt/FTDI… Thanks!
=> Use threading in VinceUSBDMX512 plugin and fix it

.github/workflows/build.yml
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Fix deprecated nodejs16 actions

resources/fixtures/beamZ/beamZ-PS10W.qxf
Hi! I Added beamZ PS10W fixture mapping. There is no info about DMX modes in the manual, so manually tested them. Should be all good and tested the mappings, works perfectly.
Manual here: https://www.beamzlighting.com/product/ps10w-led-pin-spot-10w-4-in-1-dmx/
=> Added beamZ PS10W fixture

webaccess/res/Test_Web_API.html
#1559 Added animation widget preset buttons in Web API test page
=> Animation widget in Web API test page.

ui/src/qlcplus_ca_ES.ts, ui/src/qlcplus_es_ES.ts
Updated catalan and spanish UI Translations.
=> Updated catalan and spanish UI Translations.

ui/src/showmanager/sequenceitem.cpp
=> ui: SequenceItem draws step note-text in ShowEditor timeline

plugins/gpio/GPIO_ca_ES.ts, plugins/gpio/GPIO_es_ES.ts, plugins/hid/HID_ca_ES.ts, plugins/hid/HID_es_ES.ts, qmlui/qlcplus_ca_ES.ts, qmlui/qlcplus_es_ES.ts, ui/src/qlcplus_ca_ES.ts, ui/src/qlcplus_es_ES.ts, webaccess/src/webaccess_ca_ES.ts, webaccess/src/webaccess_es_ES.ts
Updated Catalan translation.
Fixed some typos in catalan translation.
Updated Spanish Translation
=> Updated Catalan translation.

resources/fixtures/Eurolite/Eurolite-LED-TSL-1000-Scan-MK2.qxf, resources/fixtures/Varytec/Varytec-LED-Theater-Spot-100.qxf
Added fixtures for 
- Eurolite LED-TSL 1000 Scan MK2
- Varytec LED Theater Spot 100
=> New Fixtures for Eurolite and Varytec

CMakeLists.txt, translate.sh
- Updated the translate.sh to support Qt6.
- Modified CMakeLists to install *.qm files during make install.
=> Qt6 Translation Issue

engine/audio/src/audiorenderer_qt5.cpp, engine/audio/src/audiorenderer_qt6.cpp
It will make lintian happy when building Debian package…
=> engine: fix minor spelling errors

platforms/linux/org.qlcplus.QLCPlus.appdata.xml, platforms/linux/org.qlcplus.QLCPlusFixtureEditor.appdata.xml
I have tried to find the same screenshots from the website but feel free to change them as needed!
=> Fix screenshot URLs in AppData

resources/rgbscripts/devtool.html, resources/rgbscripts/devtool/devtool.js
While working with the RGB script devtool I cam across a couple of tiny things that I thought could be improved. Nothing major, just basic stuff.
- Every form control now has a label (to comply with [WCAG 2.0 H44](https://www.w3.org/TR/WCAG20-TECHS/H44.html))
- The buttons now have nice UTF-8 symbols
- Some tables had invalid columns
- There were some typo's
=> Various small things in RGB script devtool

resources/rgbscripts/devtool.html, resources/rgbscripts/devtool/devtool.js
Tested on Ubuntu Linux in Firefox and Chromium.
=> Add browse and drag-and-drop support for loading RGB scripts

engine/src/grandmaster.h, ui/src/virtualconsole/vcdockarea.cpp, ui/src/virtualconsole/vcdockarea.h, ui/src/virtualconsole/vcproperties.cpp, ui/src/virtualconsole/vcproperties.h, ui/src/virtualconsole/vcproperties.ui, ui/src/virtualconsole/vcpropertieseditor.cpp, ui/src/virtualconsole/vcpropertieseditor.h, ui/src/virtualconsole/virtualconsole.cpp, webaccess/res/virtualconsole.css, webaccess/src/webaccess.cpp
Also requested in the forum a couple of times: [1](https://forum.qlcplus.org/viewtopic.php?p=77209) [2](https://forum.qlcplus.org/viewtopic.php?p=77016) [3](https://forum.qlcplus.org/viewtopic.php?p=75331).
=> Add ability to hide Grand Master on virtual console and web

resources/fixtures/Cameo/Cameo-Wookie-series.qxf, resources/fixtures/Eurolite/Eurolite-LED-TMH-40.qxf, resources/fixtures/Eurolite/Eurolite-TMH-40.qxf, resources/fixtures/Stairville/Stairville-HF-900-Haze-Fogger.qxf
add fixtures:
- Eurolite LED TMH-40
- Stairville HF-900 Haze Fogger
=> add fixture Eurolite-TMH-40.qxf

debian/changelog, resources/fixtures/FixturesMap.xml, resources/fixtures/Sagitter/Sagitter-ARS1500FC.qxf, resources/fixtures/Sagitter/Sagitter-Lite-Beam-5R.qxf, resources/fixtures/Sagitter/Sagitter-Prince.qxf, resources/inputprofiles/M-Wave-SMCMixer.qxi
Added fixture definitions for:
- Sagitter Prince
- Sagitter Lite Beam 5R
- Sagitter ARS1500FC
Fixture validator check passed.
Manuals for revision:
Prince - https://www.proel.com/image/data/sagitter/SG%20PRINCE-1.pdf
Lite Beam 5R - https://contents.proel.com/image/data/sagitter/SG%20LTBEAM5R-10R%20A4.pdf
ARS 1500FC - https://contents.proel.com/image/data/sagitter/SG%20ARS1500FC.pdf
Also updated FixtureMap.xml and Changelog
=> resources: 3 new fixtures

engine/src/fixturegroup.cpp, engine/src/function.cpp, engine/src/inputpatch.cpp, engine/src/outputpatch.cpp, engine/src/qlcfixturemode.cpp, engine/src/rgbmatrix.cpp, engine/src/scene.cpp, engine/src/universe.cpp, plugins/midi/src/common/midiplugin.cpp, qmlui/virtualconsole/vcframe.cpp, qmlui/virtualconsole/virtualconsole.cpp, ui/src/virtualconsole/vcwidget.cpp, webaccess/src/qhttpserver/qhttpresponse.cpp
also do not create temporary keys container,
iterate directly over map
=> simplify work with containers

engine/src/genericfader.cpp, engine/src/genericfader.h
reproducible with 12 Tri - 12 RW - 11 Strobo - 12 Moving Heads.qxw
=> GenericFader: protect map to fix crash
