mcallegari/qlcplus

- ui/src/virtualconsole/vcframe.cpp
- ui/src/virtualconsole/vcframe.h
- ui/src/virtualconsole/vcframeproperties.cpp
- ui/src/virtualconsole/vcframeproperties.h
- ui/src/virtualconsole/vcframeproperties.ui
With this checkbox checked, going further that the last page will take back to the first page.
And going before the first page will take to the last page.
> VCFrames: allow to enable page scroll loop

- .travis-ci.sh
- .travis.yml
You'll need to turn it on at http://travis-ci.org, having signed in with your Github account. It will then build all PRs.
> Enable Travis for QLC+

- debian/changelog
- engine/src/collection.cpp
As of now, the intensity of a collection is not passed down to it's member functions.
> Collection: pass down intensity

- plugins/enttecwing/src/enttecwing.cpp
- plugins/enttecwing/src/enttecwing.h
- plugins/enttecwing/src/playbackwing.cpp
- plugins/enttecwing/src/playbackwing.h
- plugins/enttecwing/src/wing.h
- plugins/enttecwing/test/wing_test.cpp
- resources/inputprofiles/Enttec-PlaybackWing.qxi
- ui/src/virtualconsole/vcframe.cpp
- ui/src/virtualconsole/vcwidget.cpp
Finally implemented syncing between widgets in the virtual console and sliders of the playbackwing by using Feedback.
If wing sliders and widget values in the virtual console differ, in case of page changes or changing stuff with the mouse, the wing slider have to fetch the current values in the virtual console, before sending new input. This prevents jumping of the output values.
With this commit also pages/page changes are fully supported for the playbackwing, when using the frame widget. Page changes work in booth directions (qlcplus -> wing, wing -> qlcplus). 
I only had to make two little changes outside the plugin (vcframe.cpp, vcwidget.cpp). Hope this is ok, I added some comments there for review.
offtools
> Enttec Playbackwing using Feedback to sync widget values and playbackwing sliders 

- resources/fixtures/Eurolite-LED-SLS-X-QCL.qxf
- resources/fixtures/FixturesMap.xml
Add definition file Eurolite-LED-SLS-X-QCL.qxf (via manual) that matches the SLS-5 QCL and SLS-12 QCL. Physical data taken from SLS-12 QCL.
> Euro lite ledslsqcl

- plugins/ola/olaoutthread.cpp
Correct a bug in which output shorter than a full 512 channels sends uninitialized data to the OLA server.  Now fills buffer with zero bytes before copy.  Uses Massimo's suggested version of the change.
> OLA:  Initialize output buffer with zeros

- plugins/ola/olaio.cpp
Added a compiler preprocessing macro, QLC_OLA_FIRST_UNIVERSE, which allows the OLA plugin to be built with a different starting universe number.  Also, updates code for user display of universe number.  This commit does not represent any user-facing changes unless the module is compiled with a different starting universe number.
> added compile option to change OLA plugin starting universe

- engine/src/efx.cpp
- engine/src/efxfixture.cpp
- engine/src/efxfixture.h
- engine/src/gradient.cpp
- engine/src/gradient.h
- engine/src/src.pro
- engine/test/efx/efx_test.cpp
- engine/test/efxfixture/efxfixture_test.cpp
- ui/src/efxeditor.cpp
- ui/src/efxeditor.h
- ui/src/efxeditor.ui
- ui/src/efxpreviewarea.cpp
- ui/src/efxpreviewarea.h
- ui/test/efxpreviewarea/efxpreviewarea_test.cpp
I have implemented an improved version of EFX generator to support more parameters other than classic Pan & Tilt.
This version has the following improvements:
- support RGB, Dimmer and Pan & Tilt for each fixture; 
- support parameters mix inside the same EFX;
- has a better EFX preview with RGB feedback and better preview on efx test;
> New modes for the EFX editor

- resources/fixtures/Chauvet-Intimidator-Spot-LED-150.qxf
Both tilt channels had the same byte value.
> Fixed Chauvet Intimidator Spot LED 150 Tilt Fine group

- engine/src/efxfixture.cpp
- engine/src/efxfixture.h
- engine/src/gradient.cpp
- engine/src/gradient.h
- ui/src/clickandgowidget.cpp
- ui/src/efxpreviewarea.cpp
Gradient size should be 255x255 because it is accessed by EFX when RGB mode is used.
After my initial commit, gradient x size was changed to 252 to reflect the ClickAndGoWidget size.
Now I have correct the Gradient and the  ClickAndGoWidget x size to 255.
> EFX gradient size should be 256x256

- resources/fixtures/Martin-24-7-Hazer.qxf
Created on 31/08/15.
Changed capabilities to better reflect the manual (output instead of speed for haze output etc.).
https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CCEQFjAAahUKEwicy9XKyvjHAhWKHxoKHcz4BA0&url=http%3A%2F%2Fwww.eventuryproductions.com%2Fdocuments%2Fproducts%2Flicht%2Fjem_zr24-7_hazer_manual.pdf&usg=AFQjCNEJO99LOMW7j7AKCuO5SY35vgP57g&sig2=h5nQAZZuNRbur1c1yiSb5g
> New fixture Martin ZR24/7 Hazer

- resources/fixtures/Blizzard-Lighting-Stimul-Eye.qxf
Created on 04/09/15.
The 12 channel mode was completely wrong. Other minor changes to better match the manual.
http://www.blizzardlighting.com/products/moving-head-lights/download/4681/571/65
> New fixture - Blizzard Lighting Stimul-Eye

- resources/fixtures/Stairville-LED-Show-Bar-Tri-18x3W-RGB.qxf
Created on 11/07/15. Converted from German and added heads.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8719
Manual here:
http://www.thomann.de/gb/stairville_show_bar_triled_18x3w_rgb.htm
> New fixture - Stairville LED Show Bar Tri 18x3W RGB

- ui/src/speeddial.cpp
- ui/src/src.pro
- ui/src/virtualconsole/vcmatrix.cpp
- ui/src/virtualconsole/vcmatrix.h
- ui/src/virtualconsole/vcmatrixproperties.cpp
- ui/src/virtualconsole/vcmatrixproperties.h
- ui/src/virtualconsole/vcspeeddial.cpp
- ui/src/virtualconsole/vcspeeddial.h
- ui/src/virtualconsole/vcspeeddialpreset.cpp
- ui/src/virtualconsole/vcspeeddialpreset.h
- ui/src/virtualconsole/vcspeeddialproperties.cpp
- ui/src/virtualconsole/vcspeeddialproperties.h
- ui/src/virtualconsole/vcspeeddialproperties.ui
VCSpeedDialProperties: Add a tab to edit presets
When clicking on a preset, the speed dial value is changed
Like the VCAnimation, it's possible to assign an external input to each preset button
TODO:
- Add a button on the SpeedDial to "Save" current value in a new preset in live
- rework the multiplier functionnality ?
> VCSpeedDial Presets

- etc/qlcplus-fixtureeditor.desktop
- etc/qlcplus.desktop
- etc/qlcplus.nsi
- etc/qlcplus.xml
- etc/qlcplusQt5.nsi
1. added Czech to various files like NSIS installer, linux desktop files, etc.
2. added all languages that have translation to NSIS installer
3. added new types (qxi, qxmt) to mime-types definition
I suggest that translators have a look at these files as well - many of the translations are missing.
I didn't test NSIS installer how it looks like with these changes.
> Language fixes

- ui/src/speeddial.cpp
- ui/src/speeddial.h
- ui/src/virtualconsole/vccuelistproperties.cpp
- ui/src/virtualconsole/vcspeeddial.cpp
- ui/src/virtualconsole/vcspeeddial.h
- ui/src/virtualconsole/vcspeeddialproperties.cpp
- ui/src/virtualconsole/vcspeeddialproperties.h
- ui/src/virtualconsole/vcspeeddialproperties.ui
- The multi/div buttons are applied AFTER the dial's value
- The resulting value is displayed on the side
- There is a reset button to reset the current factor
- There is a checkbox that makes the factor reset when
the dial value changes (example: click on the +/- button
or select a preset)
The speed dial:
The properties:
- An input can be assigned to each button
I'm not sure about the style, it looks kinda big and ugly, and the result label is not visible enough. (translation: it looks like shit)
But the behavior is less random than the current implementation :)
> VCSpeedial: put mult/div buttons outside of the dial

- resources/fixtures/LiteCraft-LED-PAR-64-AT3.qxf
Another simple fixture. There are two 'Color Macro Modes' since the manual is not clear they behave the same and the maths doesn't add up
First description (1/2-channel mode): 35 colours + black => 7 each (245) + 11 for black?
Second description (7-channel mode): 0-13: No macro (RGB mode), 14-255: pre-programmed colors => 35 does not go into this number but 22 would (11 values per colour??).
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=8987
> New fixture - LiteCraft LED PAR 64 AT3

- fixtureeditor/fixtureeditor_fr_FR.ts
- plugins/E1.31/E131_fr_FR.ts
- plugins/artnet/src/ArtNet_fr_FR.ts
- plugins/dmx4linux/DMX4Linux_fr_FR.ts
- plugins/dmxusb/src/DMX_USB_fr_FR.ts
- plugins/enttecwing/src/ENTTEC_Wing_fr_FR.ts
- plugins/hid/HID_fr_FR.ts
- plugins/loopback/src/loopback_fr_FR.ts
- plugins/midi/MIDI_fr_FR.ts
- plugins/ola/OLA_fr_FR.ts
- plugins/osc/OSC_fr_FR.ts
- plugins/peperoni/Peperoni_fr_FR.ts
- plugins/spi/SPI_fr_FR.ts
- plugins/udmx/src/uDMX_fr_FR.ts
- plugins/velleman/src/Velleman_fr_FR.ts
- ui/src/qlcplus_fr_FR.ts
- webaccess/src/webaccess_fr_FR.ts
Changes are open for discussion, it would be nice to have a french translator to talk to :)
Rest of description in french to start the discussion: (unless @mcallegari feels the discussion should happen in private)
Je n'ai jamais utilisé QLC+ traduit en français, donc je ne sais pas ce que mes remarques valent.
Le changement principal introduit ici, c'est la traduction de fixture. Je ne sais pas comment c'est traduit dans les autres logiciels, mais "projecteur", ça n'englobe pas toutes les "fixtures", qui peuvent être des machines à fumée, des lance-flammes, etc.
Donc pour remplacer "projecteur" -> "appareil".
Appareil, ça fait un peu aspirateur. Mais on peut très bien avoir un aspirateur piloté en DMX !
Ensuite, dans le fixture definition editor, on a le mot "head" qui revient plusieurs …
> French translation: lots of changes v2

- resources/fixtures/Chauvet-DMX-Mega-Strobe-III.qxf
Added physical data, deleted Blaster Modes (it's an effect, not a mode).
Entered power as 75W (1/10th of bulb power - guessed).
Google:
chauvet dmx medastrobe iii
> Fixture update - Chauvet-DMX-Mega-Strobe-III

- resources/fixtures/SGM-Victory-250.qxf
Added physical data, gobos and click and go colours.
DMX data:
http://www.techref.info/web/ref/dmx/sgm/r-vic.php
Manual:
Google sgm victory 250 manual then select Victory_250 - Madman Production for colours and gobos.
> Fixture update - SGM-Victory-250

- resources/fixtures/Talent-BL63-10-LED-Bar.qxf
Added physical data (yawn...), missing ranges in the strobe and created a new channel dual functionality in 7-channel mode.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9109
> New fixture - Talent-BL63-10-LED-Bar

- resources/fixtures/GLP-Junior-Scan-1.qxf
Updated physical data, colours and gobos. A lot of the gobos are approximate.
Found physical data for the '1' model here:
http://www.jenashop.nl/junior-scan1-silver-250w-p-392.html?osCsid=93feainc076io32r6hvlo38024
> Fixture update - GLP-Junior-Scan-1

- resources/fixtures/Robe-Robin-MiniMe.qxf
Added pan, tilt and beam angle (theta = arctan (2m/7m) from datasheet.
https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=0CCcQFjABahUKEwiiouTgofnIAhUK1xoKHXJGBcE&url=http%3A%2F%2Fwww.robe.cz%2Ffileadmin%2Frobe%2Fdownloads%2Fuser_manuals%2FUser_manual_Robin_MiniMe.pdf&usg=AFQjCNFKpXmpo7-bg8vYQvs3ggsM4Ek1nQ&sig2=eFuaG3tqIn9ITOlw5t93qw&cad=rja
> Fixture update - Robe-Robin-MiniMe

- resources/fixtures/JB-Systems-The-WinnerII.qxf
Added pan/tilt information, click and go colours and gobos. Only the hand gobo is really bad but it is indicative. Gobo images in the datasheet.
https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=9&ved=0CDsQFjAIahUKEwiaxdWMiPnIAhWBzxoKHXcPDCQ&url=https%3A%2F%2Fcontrollux.com%2Fdownloads%2Fwebshop%2FJBS-40034004%2Fthe-rover-product-manual.pdf&usg=AFQjCNHglJXaZ815j_A78heoEVRbJalaTw&sig2=6PeXNe0UHCViZimybwMb-g&cad=rja
> Fixture update - JB-Systems-The-WinnerII

- resources/fixtures/Chauvet-Q-Spot-260-LED.qxf
- resources/fixtures/Eurolite-KLS200.qxf
Updated physical data and click and go colours. No gobo images found on the web.
https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCIQFjABahUKEwikqIrBofnIAhWH6xoKHf59BjE&url=http%3A%2F%2Fwww.chauvetprofessional.com%2Fwp-content%2Fuploads%2F2015%2F07%2FQ-Spot_260-LED_UM_Rev-02-1-30-12DEC.pdf&usg=AFQjCNGOQgseHRuWEgdTfERNEkqNCCv3Lw&sig2=EYBiGyutT8xJYi3ZVV9cMg
> Chauvet q spot 260 led

- ui/src/virtualconsole/vcxypadproperties.cpp
- ui/src/virtualconsole/vcxypadproperties.h
- ui/src/virtualconsole/vcxypadproperties.ui
Hi everyone, this pull request add the possibility to manual sorting presets on vcxypad, that is very usefull for widgets with a high preset number.
I have implemented the behaviour and look & feel with up/down buttons similar to other components.
> Add manual sort for presets on vcxypad

- engine/src/chaserrunner.cpp
- ui/src/virtualconsole/vccuelist.cpp
- ui/src/virtualconsole/vccuelist.h
Fix for #672 
When using the faders, the current step moves in the VCCueList,
but not in ChaserRunner.
ChaserRunner::m_lastRunStepIdx is the last step that was run
before using the faders.
This means that when calling ChaserRunner::next(), the next index
it not the one pointed at by the VCCueList.
Fix: let ChaserRunner::stopStep change the current chaser step, and inform the VCCueList through the currentStepChanged() signal.
> Cuelist: fix issue when using the next button after the crossfader

- plugins/udmx/src/udmxdevice.cpp
- plugins/udmx/src/z65-anyma-udmx.rules
Propose to add support for the UDMX clone from AVLdiy.cn with non-standard VID/PID 03eb:8888.
I bought this cable from DealExtreme and found out, that it doesn't work with QLC+ because of different USB vid/pid. Device is tested and works with changes, proposed in my commit.
Detects as:
[39684.701431] usb 3-1.3: New USB device found, idVendor=03eb, idProduct=8888
[39684.701437] usb 3-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[39684.701440] usb 3-1.3: Product: D512
[39684.701442] usb 3-1.3: Manufacturer: AVLdiy.cn
[39684.701445] usb 3-1.3: SerialNumber: AVLdiy.cn0001
PS: It's my first contribution to the open source project, so please point out any mistakes.
> Add support for the AVLdiy.cn UDMX clone with non-standard VID/PID

- README
Website has moved. Download pages are now at http://download.qt.io/official_releases/qt/
> Update QT links

- engine/src/qlccapability.cpp
- engine/src/qlccapability.h
- engine/src/qlcchannel.cpp
- engine/src/qlcchannel.h
- fixtureeditor/editchannel.cpp
- fixtureeditor/editchannel.ui
A message is displayed as long as the range is invalid, and the values are not applied.
http://qlcplus.org/forum/viewtopic.php?f=5&t=9167&start=10
> Channel editor: allow temporary invalid cap ranges

- engine/src/universe.cpp
- engine/src/universe.h
Change processing of DMX input data so that:
- the input data is not affected by the grandmaster and channel modifiers
- the input data is merged with QLC+ in a HTP fashion (for all channels, regardless of channel settings)
- the input data is shown in DMX monitor
Usage scenarios:
- QLC+ as DMX sniffer (this requires to patch enough dimmer channels)
- QLC+ as DMX visualizer (in 2D view mode, requires proper fixture patching)
- QLC+ on raspberry just forwards data from QLC+ on PC while programming scenes;
when the workspace is transferred, Raspberry becomes main controller; the devices are
always connected to RPi
> DMX monitor: Show data from passthrough

- resources/fixtures/Stairville-LED-Matrix-Blinder-5x5.qxf
This had the 4-channel mode missing and the 28-channel mode was completely wrong.
Link to original definition and manual:
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9195
> New fixture - Stairville-LED-MAtrix-Blinder-5x5

- ui/src/virtualconsole/vcslider.cpp
This way sliders in playback mode have the same behavior
as the sliders on a VCCueList.
Start a function with a slider -> manual fade in.
Stop a function with a slider -> manual fade out.
http://qlcplus.org/forum/viewtopic.php?f=12&t=9228
> VCSlider: ignore fade in and fade out times

- resources/fixtures/American-DJ-WiFly-EXR-HEX5-IP.qxf
Datasheet here:
http://www.adj.com/wifly-exr-hex5-ip
Click & Go colours are normalized to 255 accept black and UV. There is a deliberate mistake in [4-7] Color Macros where I missed out 'Red' 10 seconds after pushing the file. ;/
> New fixture - American-DJ-WiFly-EXR-HEX5-IP

- plugins/dmxusb/src/src.pro
- plugins/hid/hid.pro
- plugins/peperoni/unix/unix.pro
- plugins/spi/spi.pro
- plugins/udmx/src/src.pro
- variables.pri
Add the UDEVRULESDIR variable to let packagers change the location of the udev rules directory in one place. Because some distributions of linux don't use "/etc/udev/rules.d" for the rules but something like "/usr/lib/udev/rules.d"
> (FIX): add a variable for the udev rules path

- etc/Info.plist
Change Info.Plist according to http://blog.qt.io/blog/2013/04/25/retina-display-support-for-mac-os-ios-and-x11/
> Add support for Retina displays on MacOSX (Fix #733)

- etc/etc.pro
- etc/qlcplus-fixtureeditor.appdata.xml
- etc/qlcplus.appdata.xml
- plugins/E1.31/E1.31.pro
- plugins/E1.31/qlcplus-e131.metainfo.xml
- plugins/artnet/src/qlcplus-artnet.metainfo.xml
- plugins/artnet/src/src.pro
- plugins/dmx4linux/dmx4linux.pro
- plugins/dmx4linux/qlcplus-dmx4linux.metainfo.xml
- plugins/dmxusb/src/qlcplus-dmxusb.metainfo.xml
- plugins/dmxusb/src/src.pro
- plugins/enttecwing/src/qlcplus-enttecwing.metainfo.xml
- plugins/enttecwing/src/src.pro
- plugins/hid/hid.pro
- plugins/hid/linux/qlcplus-hid.metainfo.xml
- plugins/loopback/src/qlcplus-loopback.metainfo.xml
- plugins/loopback/src/src.pro
- plugins/midi/midi.pro
- plugins/midi/qlcplus-midi.metainfo.xml
- plugins/ola/ola.pro
- plugins/ola/qlcplus-ola.metainfo.xml
- plugins/osc/osc.pro
- plugins/osc/qlcplus-osc.metainfo.xml
- plugins/peperoni/unix/qlcplus-peperoni.metainfo.xml
- plugins/peperoni/unix/unix.pro
- plugins/spi/qlcplus-spi.metainfo.xml
- plugins/spi/spi.pro
- plugins/udmx/src/qlcplus-udmx.metainfo.xml
- plugins/udmx/src/src.pro
Appdata files get used by software-center on ubuntu, gnome-software-centre on fedora and other software centers. This also gives room for seperate icons and info for plugins if we implement a ".metainfo.xml" file for them. The plugins most likely also get listed underneath the package they extend.
For more info on appdata go [here](http://www.freedesktop.org/software/appstream/docs/chap-Metadata.html) and for more info on metainfo go [here](http://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Addons.html).
> Add appdata files and install them

- etc/qlcplus.appdata.xml
Just saw that there were two "nl" entries. German translation will follow ...
> Fix language declaration of italian translation

- engine/src/inputoutputmap.cpp
- engine/src/inputoutputmap.h
- engine/test/inputoutputmap/inputoutputmap_test.cpp
- ui/src/inputoutputmanager.cpp
Forbid creating gaps in the universe list
by deleting a universe that is not the last one.
When loading a workspace that contains gaps in
the universe list, fill the gaps.
This fixes various issues and crashes that happen
when a gap is present in the universe list.
Related thread in the forum: http://qlcplus.org/forum/viewtopic.php?f=5&t=9303
This is open for discussion.
After struggling with the 'only use universe ID' solution (that touches a lot of files and can be seen here https://github.com/plugz/qlcplus/tree/universeindex-fix-2), and realising that the qmlui code uses universes indexes everywhere, and that I don't know shit about qml... I gave up and came up with a way more simple solution to this issue:
Force universeID==universeIndex
Pros of this solution: no more id/index …
> Force universe ID and Index to be the same

- plugins/E1.31/e131controller.cpp
- plugins/E1.31/e131controller.h
- plugins/E1.31/e131plugin.cpp
- plugins/E1.31/e131plugin.h
- plugins/artnet/src/artnetcontroller.cpp
- plugins/artnet/src/artnetcontroller.h
- plugins/artnet/src/artnetpacketizer.cpp
- plugins/artnet/src/artnetpacketizer.h
- plugins/artnet/src/artnetplugin.cpp
- plugins/artnet/src/artnetplugin.h
- plugins/artnet/src/configureartnet.cpp
- plugins/osc/oscpacketizer.h
- plugins/osc/oscplugin.cpp
- plugins/osc/oscplugin.h
- Each controller binds on its own IP address instead of ANY address, allowing to send ArtNet to several different networks
- ArtPoll is sent every 5 seconds so lost packets are less of an issue
- Configuration: can select any input ArtNet universe
This has been tested on windows & linux, not on OSX.
> ArtNet plugin rework

- qlc.pro
- translate.sh
This fix
- removes the "-silent" parameter from the call to lrelease since that is not a real parameter
- makes use of bash variables to specify the names of files in translate.sh
- makes the translate files install by putting "./" in front of the file names
> Fix translate

- debian/changelog
- engine/src/audio/audiocapture.cpp
- engine/src/audio/audiocapture.h
- engine/src/audio/audiocapture_alsa.cpp
- engine/src/audio/audiocapture_alsa.h
- engine/src/audio/audiocapture_portaudio.cpp
- engine/src/audio/audiocapture_portaudio.h
- engine/src/audio/audiocapture_qt.cpp
- engine/src/audio/audiocapture_qt.h
- engine/src/audio/audiocapture_wavein.cpp
- engine/src/audio/audiocapture_wavein.h
- engine/src/doc.cpp
- engine/src/rgbaudio.cpp
- ui/src/inputoutputpatcheditor.cpp
- ui/src/virtualconsole/vcaudiotriggers.cpp
I made a little test for audio input stability:
- Create an RGB matrix in audio mode
- Create a chaser with just the matrix in it, with duration=0
- play the chaser
- go to the I/O tab, and mess with the audio input configuration
This makes QLC+ crash quite quickly.
With this patch, QLC+ does not crash.
What it does:
- AudioCapture::uninitialize() does the Audio uninitialization (instead of doing it in the destructor)
- AudioCapture::initialize() and AudioCapture::uninintialize() are called in the AudioCapture Thread. This way Qt objects (QAudioInput) are created and destroyed from the same thread. Qt likes this better.
- This allow AudioCapture::run() to know when initialization could not be achieved, and abandon reading.
Tested on Linux (Qt5 version, Qt4 version)
I will test on Windows …
> fix crash: select another input while rgbaudio is running

- debian/changelog
- ui/src/rgbitem.cpp
- ui/src/rgbitem.h
- ui/src/rgbmatrixeditor.cpp
- ui/src/rgbmatrixeditor.h
Fix #749 
Also fix a bug that was here from the beginning of times: fadeout "tail" size way too big and sometimes stucked
Issue not fixed: the fadein "tail" is never seen because the tick of the preview is based on the duration of the rgbmatrix. As the duration of the rgbmatrix is FadeIn+Hold, the fadein is never seen.
I propose 3 solutions:
- Calculate a better tick for the rgbmatrix preview (based on greatest common divisor of fadein and hold ?)
- Go back to previewTick == MasterTimerTick
- Not care about this
> Rgbmatrix preview fix

- engine/src/qlcfixturedef.cpp
- ui/src/app.cpp
This way, in case of a crash during saving,
the current destination file will not become blank or corrupt.
Idea here:
http://qlcplus.org/forum/viewtopic.php?f=5&t=9227&p=40548&hilit=crash+while+saving#p40548
> Save in temp file before replacing destination file

- resources/fixtures/OXO-LED-Funstrip-DMX.qxf
For manual link see bottom post of this page:
http://www.qlcplus.org/forum/viewtopic.php?f=6&t=9540&p=41956#p41956
I have not included 'Program Master' (dimmer) as part of the heads. The manual suggests it is for the built in programs only but there is no proof. This is only a white fixture so I'm not sure if it matters much.
> New fixture - OXO-LED-Funstrip-DMX

- engine/audio/src/audiocapture.h
- engine/audio/src/audiocapture_qt.cpp
- engine/audio/src/audiocapture_qt.h
fix #795 
The issue is that neither QAudioInput::bytesReady()
nor QIODevice::bytesAvailable() are reliable here.
The only solution is to simply call QIODevice::read()
and use its return value.
> fix audiocapture_qt

- resources/fixtures/Cameo-LED-RGBW-PAR64-18x8W.qxf
- resources/fixtures/Stairville-MH-X60th-LED-Spot.qxf
Updated fixture:
New version has fixed the macro channels which differ between the operating modes.
Mode 2 is colours only. Modes 3 (1) and 7 have colours and macros.
http://www.qlcplus.org/forum/viewtopic.php?f=3&t=9620
> Cameo led rgbw par64 18x8 w

- plugins/E1.31/e131controller.cpp
- plugins/osc/osccontroller.cpp
- plugins/osc/osccontroller.h
- plugins/osc/oscpacketizer.cpp
- plugins/osc/oscpacketizer.h
Also use safer pointers
Fix #833
I also tested #832
Without this patch, QLC+ crashes when unchecking/checking 2 times the input of a line with feedback enabled.
With this patch, no crash, and the input still works.
So maybe it fixes #832 too, or maybe my test procedure was wrong.
> osc rework: fix receiving packets on wrong interface

- ui/src/virtualconsole/vcframe.cpp
Pagenumber is now shown for collapsed frames
The page navigation buttons are still hidden
hide the navigation button on initializing a collapsed multipaged frame too
The discussion thread is here:
http://www.qlcplus.org/forum/viewtopic.php?f=12&t=10125
> show pagenumber on multipage frames when frame is collapsed

- plugins/gpio/gpioplugin.cpp
- plugins/gpio/gpioplugin.h
- plugins/gpio/gpioreaderthread.cpp
GPIO inputs are noisy. Even with good power supplies and proper electronics in the front you get occasional false triggers (I had 2 last summer. One by itself before the show and one when someone stepped on some cables). This patch requires the value to be stable for 200ms before we accept the trigger as real. The hysteresis work both ways so you also check for release of the button.
It does slow down the response from a button press by 200ms. But on the other hand you can also use internal pull-ups and cheap power supplies without problems with your buttons.
The best thing is that you get no false triggers. And that is quite important for the end user.
> Hysteresis

- resources/docs/addrgbpanel.html
- ui/src/addrgbpanel.cpp
- ui/src/addrgbpanel.h
- ui/src/addrgbpanel.ui
- ui/src/fixturemanager.cpp
Had to work with panels where LED pixels were interconnected top to bottom instead of side to side and it was easier for me to add this feature to code than to figure how to transpose matrices myself. Hopefully others will find this feature useful as well.
If any code release forms have to be signed by me, I will gladly do that.
> Added direction to RGB panel creation dialog.

- debian/qlcplus.postinst
- debian/qlcplus.postrm
As suggested by https://lintian.debian.org/tags/maintainer-script-lacks-debhelper-token.html
> Debian packaging

- ui/src/createfixturegroup.ui
- ui/src/fixturegroupeditor.ui
Fixture group maximum dimensions are limited in UI. One can easily create fixture group larger than 99px by 99px by adding RGB panel, but can not enter dimensions larger than 99px by 99px in fixture group editor or create dialog.
I increased limit to 999, which should suit most of us for time being.
> Increase maximum fixture group dimensions that UI accepts as valid.

- ui/src/virtualconsole/vcwidget.cpp
Uses recently added acceptsInput() method since a disabled widget should not send any feedback from my point of view. If you care, it could be renamed or another sendsFeedback() could be added. Just let me know if you want something to change.
Fixes: #923
> Fixed unexpected feedback from another page

- ui/src/inputselectionwidget.cpp
This fixes the problem that the "Choose external input" dialog does not consider page numbers if it's executed in a multipage frame.
Reported here: http://www.qlcplus.org/forum/viewtopic.php?f=33&t=10612&p=46219
> Fixed choose external input does not consider page number

- webaccess/res/websocket.js
- webaccess/src/webaccess.cpp
I'm opening this PR to start a discussion about web console.
It is a great idea, but still requires a lot of improvements.
I'm starting this with fix for sliders in inverted and percentage modes.
Test console for this one: http://pastebin.com/effRheTr
As stated in the commit I see these possible improvements for sliders:
- Properly using min/max values to span the whole slider
range from min to max, not 0 to 255.
- Sliders in 'knob' mode - they should use some other input
method, maybe a simple numeric up/down (or textbox) ?
That might be useful for someone.
- It would be nice to have horizontal sliders, but that also
means implementing them in VC, so probably won't be done.
I'll also work on #933
What other things should be prioritized as far as webaccess is concerned?
Personally I would …
> Webaccess improvements

- ui/src/virtualconsole/vcframe.cpp
This fixes the problem, that when copying a frame in vc, the keySequences for enabling and previous/next page are not copied.
> VC: Fixed frame's keySequences not copied

- ui/src/virtualconsole/vccuelist.cpp
This fixes the issue that the sliders Mode status is not copied.
Reported here: http://www.qlcplus.org/forum/viewtopic.php?p=46703#p46703
> VC/Cue List Widget: Fixed sliders Mode not copied

- ui/src/virtualconsole/vcwidget.cpp
This fixes the issue reported here: http://www.qlcplus.org/forum/viewtopic.php?f=33&t=10796
I'm still not sure if the use case is intended by QLC+, so if a disabled frame should send any feedback. But if it is considered as expected, we could simply use the visibility status of a widget in addition to the `acceptsInput` method (still needed for collapsed frames, in which the widgets are hidden).
> Fixed no feedback from widgets in disabled frames

- ui/src/app.cpp
By default, Qt does not enable standard Alt-key mnemonics on MacOS. This commit lets QLC+ on MacOS respond to Alt-key shortcuts the same as on other platforms.
This change also allows MacOS users to type the first letter of a dialog box button, the same as on Windows and Linux - for example, Y for "Yes" to "There are still running functions. Stop them?".
> Enable Alt-key shortcuts on Mac OS

- engine/src/inputoutputmap.cpp
- engine/src/universe.cpp
- engine/src/universe.h
- first commit is a simplification of code (reusing Universe::dumpOutput). This has the advantage, that blackout data are sent to all patched outputs, not just the first one (relevant only for QLC+5)
- second commit 1) changes what data is output on blackout: now instead of plain zeroes, channel modifiers are applied; 2) simplifies code structure 3) calls postGMValues() under lock (this is the change that needs the most thorough review)
- third commit updates m_usedChannels, m_totalChannels and post GM data so that data is affected immediately after CM is applied
> Channel modifiers for blackout

- ui/src/virtualconsole/vcaudiotriggersproperties.ui
- ui/src/virtualconsole/vcclock.cpp
- ui/src/virtualconsole/vcclock.h
- ui/src/virtualconsole/vcclockproperties.cpp
- ui/src/virtualconsole/vcclockproperties.h
- ui/src/virtualconsole/vcclockproperties.ui
As requested [here](http://www.qlcplus.org/forum/viewtopic.php?f=18&t=10923&p=47289) I added external input support for the clock widget in countdown and stopwatch mode.
I was not yet able to test feedback, but will this weekend.
I'm not completely sure about the order in the properties dialog but think as it is now is sufficient.
> VC/Clock: Added external inputs for controlling countdown/stopwatch

- ui/src/virtualconsole/vcspeeddialproperties.cpp
- ui/src/virtualconsole/vcspeeddialproperties.h
- ui/src/virtualconsole/vcspeeddialproperties.ui
I often have lots of functions connected to a speed dial in the virtual console where i want to control the fade times in the same way. To save a lot of clicking in the dropdown boxes I added a button to apply the factors from the selected function to the others (see screenshots).
results in
> Add copy & paste buttons to speed dial functions page

- engine/src/fixture.cpp
- engine/src/fixture.h
- qmlui/qml/fixturesfunctions/RGBPanelProperties.qml
- ui/src/addrgbpanel.cpp
This is my first pull request on GitHub, so please advise if I'm not doing something right.
I have a chain of LED pixels using WS2811 chips. For some reason they are wired in RBG channel order. I've added support for RBG in pixel panels following the examples of other channel orderings. This change seems to work in my setup, so I thought others might find it useful.
Peter
> Added support for RBG pixel panels

- webaccess/src/webaccess.cpp
- webaccess/src/webaccessauth.cpp
- webaccess/src/webaccessauth.h
This pull request fixes issues raised in previous PR (#980) discussion:
1. Qt4 doesn't support SHA256 thus is has to use SHA1 or MD5
2. SHA1 and MD5 both have been broken, so Qt5 build uses SHA256
3. This prevents passwords file from being shared between QLC+ instances with different Qt versions
4. Current implementation doesn't support salting
Changes:
======
To fix that I've changed passwords file to use a different format (backwards compatible).
Each line is now in format `username:passwordHash:userlevel:hashAlgorithm:salt`, where only username and passwordHash is required.
Each field explained:
- username: the login name
- passwordHash: hash of string `password + salt` using `hashAlgorithm`
- userLevel: integer expressing user access level as defined in `WebAccessUserLevel` enum in …
> Change webaccess auth file format to accommodate different hashing algorithms

- qmlui/videoprovider.cpp
- ui/src/videoprovider.cpp
As of now, the video player shows up behind other Applications (like Powerpoint) if QLC+ is not focused. I suggesst this solution, however I wasn't able to compile and test it under windows.
Cheers
> focus video player

- fixtureeditor/fixtureeditor_de_DE.ts
- plugins/E1.31/E131_de_DE.ts
- plugins/artnet/src/ArtNet_de_DE.ts
- plugins/midi/src/MIDI_de_DE.ts
- plugins/osc/OSC_de_DE.ts
- ui/src/qlcplus_de_DE.ts
- webaccess/src/webaccess_de_DE.ts
Modified whitespaces to align with source strings. No news strings to be translated.
> Fix some warnings in the german translations

- plugins/E1.31/e131packetizer.cpp
Hello!
When receiving bad/strange/incompatible packets on E1.31 port, QLC crashes because it tries to read more bytes in the packet than the packet contains.
This PR fixes the crash by rewriting the length contained in the packet data.
Another solution would be to make this check in checkPacket(), and discard the packet on wrong length.
cheers
> E1.31: fix crash on wrong packet format

- coverage.sh
- create-dmg.sh
- create-rpm.sh
- translate.sh
- unittest.sh
- replace backticks with $() (see https://mywiki.wooledge.org/BashFAQ/082)
- remove SOURCES from create_rpm.sh (unused since 2.6.2010)
> Fix .sh codacy issues

- debian/changelog
- ui/src/virtualconsole/vcaudiotriggers.cpp
- ui/src/virtualconsole/vcaudiotriggers.h
- webaccess/res/Test_Web_API.html
- webaccess/res/virtualconsole.js
- webaccess/res/websocket.js
- webaccess/src/webaccess.cpp
- webaccess/src/webaccess.h
This PR is about fixing and enhancing some WebAccess items:
- Buttons: JS events `onmousedown` and `onmouseup` replace `onclick` to be able to use Flash mode
- AudioTriggers: new signal `captureEnabled(bool)` in VCAudioTriggers allows WebAccess AudioTriggers state to be updated when changed in QLC+ directly
- Frames: possibility to use circular scrolling of pages
- Cuelist: fixes which prevented Cuelist to work correctly
More generally, I refactored the JS code to be more simple:
- move style update code from websocket.js to virtualconsole.js
- style updates are done only when receiving messages from the WS, not when clicking on the elements of the Web UI
This prevents style updates (ie. a button going green) when the element isn't actually activated in QLC+ (ie. if QLC+ is not in operate …
> Fixes and enhancements in WebAccess

- qmlui/qml/fixturesfunctions/3DView/SpotlightConeEntity.qml
- qmlui/qml/fixturesfunctions/3DView/shaders/spotlight_scattering.frag
This commit properly connects the global smoke amount setting to the volumetric scattering shader.
> connected the global smoke amount to the shaders

- qmlui/qlcplus_nl_NL.ts
I saw that the dutch translation was removed in the newest version of QLC+, so I added a translation file.
> Added dutch translation

- engine/src/qlccapability.cpp
- engine/src/qlccapability.h
- engine/src/qlcchannel.cpp
- engine/src/qlcchannel.h
- resources/fixtures/scripts/fixtures-tool.py
- resources/schemas/fixture.xsd
Some inconsistencies in channel preset lists I noticed during the development of Open Fixture Library's QLC+ 4.12.0 plugin (see [OpenLightingProject/open-fixture-library#547](https://github.com/OpenLightingProject/open-fixture-library/pull/547)).
Also, there is the `PositionPanCounterClockwise` channel preset, but no matching clockwise or Tilt presets. Is this a mistake?
When adding / removing / renaming a preset, one always needs to do so in various different places:
* XSD schema
* fixture tool
* qlcchannel.h
* qlcchannel.cpp 2 times
* qlccapability.h
* qlccapability.cpp
* maybe more "fixed" places
* and of course everywhere it is used, i.e. fixtures and code like strobe frequency preview
Would it be a good idea to add some kind of a checklist somewhere to reduce the risk of missing …
> Tidy up channel presets

- qmlui/qlcplus_de_DE.ts
The change contains two translation strings that probably were mixed up by creating.
> minor translation fix for german

- webaccess/res/virtualconsole.js
I noticed some time ago that flash buttons where not working at all in the web access mode if you are using a mobile device, and I tought it will be nice to have them working because that would make the web access even more powerful when using mobile devices.
I tested it and it works great.
Also 
```
make check
~/qlcplus_fork/qlcplus
Unit tests passed.
```
> Added flash button support at webaccess for Mobile Devices

- plugins/ola/ola.pro
I get errors when building **qlcplus** on macOS out of the box because I've installed **ola** from source.
This change to **plugins/ola/ola.pro** enables pkg-config queries on those macs where it's available, while behaving exactly as it did before otherwise (ola installed through MacPorts).
It reuses commented instructions, choosing between the two methods based on a qmake test for pkg-config existence.
> plugins/ola: enable pkg-config on macx platform

- resources/fixtures/Martin/Martin-MAC250-Krypton.qxf
Messed up in 09484275c150a2aef2b6994e0d16433f3afc4f30
PR #1166
> Fix gobo 6 visualization.

- fixtureeditor/editphysical.ui
- resources/fixtures/scripts/fixtures-tool.py
- resources/schemas/fixture.xsd
Fixes the schema for #1172 (and others like it).
I also added `3-pin IP65` and `5-pin IP65` waterproof DMX connectors, like we have in OFL. Feel free to revert that commit if you don't want them in QLC+.
> Schema updates

- engine/src/chaserstep.cpp
- engine/src/cuestack.cpp
- engine/src/fixture.cpp
- engine/src/qlcchannel.cpp
- engine/src/qlcfixturehead.cpp
- engine/src/rgbtext.cpp
- engine/src/sequence.cpp
- engine/src/showrunner.cpp
- engine/test/rgbtext/rgbtext_test.cpp
- fixtureeditor/editmode.cpp
- plugins/enttecwing/src/enttecwing.cpp
- qmlui/chasereditor.cpp
- qmlui/importmanager.cpp
- qmlui/virtualconsole/vcclock.cpp
- qmlui/virtualconsole/vcslider.cpp
- ui/src/fixtureremap.cpp
- ui/src/monitor/monitorlayout.cpp
- ui/src/rgbmatrixeditor.cpp
- ui/src/virtualconsole/vcclock.cpp
- ui/src/virtualconsole/vcmatrix.cpp
- ui/src/virtualconsole/vcslider.cpp
- ui/src/virtualconsole/vcspeeddial.cpp
- ui/src/virtualconsole/vcxypad.cpp
This patch replaces "qSort" with "std::sort" and "QFontMetrics::width" with "QFontMetrics::horizontalAdvance" if compiled with QT 5.13.
> Adaptations for Qt 5.13

- engine/src/rgbscript.cpp
- engine/src/rgbscript.h
Hi,
A small patch to fix the fact that when cloning an rgbscript, the properties are not cloned and are set to default in the new rgbscript.
> rgbscript: clone properties

- webaccess/src/webaccess.cpp
I needed a way to start a function (a show in my case) without having to create a button widget in the virtual console.
I think that such method might be useful to others so I opened this PR.
Let me know if something doesn't look right.
> Implement a 'setFunctionStatus' websocket api method

- plugins/dmxusb/src/dmxinterface.cpp
- plugins/dmxusb/src/dmxinterface.h
- plugins/dmxusb/src/dmxusb.cpp
- plugins/dmxusb/src/dmxusbconfig.cpp
- plugins/dmxusb/src/dmxusbopenrx.cpp
- plugins/dmxusb/src/dmxusbopenrx.h
- plugins/dmxusb/src/dmxusbwidget.cpp
- plugins/dmxusb/src/dmxusbwidget.h
- plugins/dmxusb/src/libftdi-interface.cpp
- plugins/dmxusb/src/libftdi-interface.h
- plugins/dmxusb/src/src.pro
This pull request adds another plugin designed for Enttec like USB DMX adapter based on FTDI RS232R chips.
Called "Open RX", it is based on the Enttec Open TX plugin code, but reads data and emits them in the software instead of writing them.
FTDI RS232 chips can send and receive signals. As a DMX widget, they are usually built with a female DMX socket, since it's the main usage.
Using a male/male adaptator and plugging in the widget in a DMX source, it can receive the signal (instead of transmitting it) and forward it to the host computer.
It has been tested with another DMX Open TX FTDI device ran by QLC. It works well and is very stable (if the computer hardware is too).
It has also been tested with a Stairville DDC-6 LCD very cheap ligthing controller. This controller vaguely speaks …
> Introducing Open RX : a way to read DMX signals via simple RSR232 FTDI chips

- plugins/E1.31/e131plugin.cpp
- plugins/artnet/src/artnetplugin.cpp
- plugins/osc/oscplugin.cpp
QNetworkInterfaces::allInterfaces() does not guarantee the order of interfaces, which can cause problems if you have many interfaces. QXW file specifies only the "line number" of the selected interface, so sometimes it can be some other interface selected different from what you set up.
For example, I have a Raspberry Pi with 6 interfaces: localhost, ethernet, wlan (hostapd, so that the customer can connect and change the scene), 2 interfaces for 3G connection, and tun (OpenVPN connection). ArtNet device is on ethernet. But, sometimes, if I restart the RPi some other interface can be selected. If that happens with wlan or 3g QLCplus floods that interface with ArtNet packet rendering that interface completely unable to respond (no 3g connection or customer not able to connect to WiFi AP). …
> Sorting of ArtNet interfaces implemented.

- engine/src/rgbscriptv4.cpp
> Don't crash when the RGB script to be parsed is empty. Fixes #1185

- platforms/linux/qlcplus-fixtureeditor.desktop
- platforms/linux/qlcplus.desktop
At least GNOME ask to add keywords to application desktop files - see [here](https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords). It is also reported by lintian with the *desktop-entry-lacks-keywords-entry* information tag. I just add some basic ones, do you see others?
I have also removed the French translation of the Name as it doesn't make sense to me to translate the software name.
> Add Keywords entry for .desktop files

- plugins/hid/hidapi.h
- plugins/hid/linux/hidapi.cpp
- plugins/hid/macx/hidapi.cpp
- plugins/hid/win32/hidapi.cpp
This update the license header of the hidapi library from upstream which is much clearer. It is needed for the upcoming Debian package (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=694077). Thanks in advance!
> Update license header of hidapi library

- platforms/macos/Info.plist
- platforms/macos/Info.plist.qmlui
The .plist need to be changed to allow the application to access microphones or soundcards.
> Mac OS audio permissions

- ui/src/audioeditor.cpp
Assuming that Default device has index = 0 in m_audioDevCombo, discovered devices are added now starting on index = 1.
> Fix wrong index in m_audioDevCombo. 

- engine/audio/src/audiocapture.cpp
- engine/audio/src/audiocapture.h
As per this thread https://www.qlcplus.org/forum/viewtopic.php?f=24&t=10301&start=10 
I have also observed an issue with the FFT part that analyses the frequencies and attempts to plot the power of the signal for different bands and trigger various functions based on the audio signal levels.  Indeed the levels are appearing too low, and for good reason.  The key problem I have identified is that the power of the signal overall should be the sum of squares of the frequency spectra magnitudes, but currently the power is estimated by finding the sum of the absolute raw signal values.
I would like to start a conversation about this part of the code, so I have changed the bits that I think are critical, but may have made mistakes regarding the bar graph as I don't yet understand the scaling …
> FFT: Fixed mono and stereo audio capture triggers based on frequency spectrum

- engine/src/chaserrunner.cpp
- engine/src/doc.cpp
- engine/src/script.cpp
- engine/test/qlcinputprofile/qlcinputprofile_test.cpp
- fixtureeditor/capabilitywizard.cpp
- fixtureeditor/edithead.cpp
- fixtureeditor/editmode.cpp
- fixtureeditor/fixtureeditor.cpp
- fixtureeditor/main.cpp
- main/main.cpp
- ui/src/ctkrangeslider.cpp
- ui/src/fixturetreewidget.cpp
- ui/src/flowlayout.cpp
- ui/src/functionselection.cpp
- ui/src/monitor/monitor.h
- ui/src/monitor/monitorlayout.cpp
- ui/src/scripteditor.cpp
- ui/test/vcbutton/vcbutton_test.cpp
- ui/test/vcwidget/vcwidget_test.cpp
- ui/test/vcxypadarea/vcxypadarea_test.cpp
- webaccess/src/webaccessauth.cpp
Everything inside Qt5 version checks, so this shouldn't break backwards compatibility.
I hope I'm right assuming (from reading similar fixes I found on the net) that with the the new generator seeding isn't needed anymore in doc.cpp. Otherwise please instruct me regarding a proper way to handle that.
> Qt5 5.15.0 deprecation fixes

- resources/rgbscripts/alternate.js
Currently, I had to make up multiple "evenodd" matrix scenes and combine them in a collection. For the simple use-case of alternating lights, I was looking to improve the efficient configuration of such an effect.
Here is an RGB script to make alternating lines and rectangles easily accessible.
I oriented myself on the plasma-style selection of colors. The script could instead also use the RGB color selector (or both standard color selectors) for the first color. Let me know if this would be better usable.
> RGB script with alternating lines and rectangles

- platforms/linux/org.qlcplus.QLCPlus.appdata.xml
- platforms/linux/org.qlcplus.QLCPlusFixtureEditor.appdata.xml
- plugins/E1.31/org.qlcplus.QLCPlus.e131.metainfo.xml
- plugins/artnet/src/org.qlcplus.QLCPlus.artnet.metainfo.xml
- plugins/dmx4linux/org.qlcplus.QLCPlus.dmx4linux.metainfo.xml
- plugins/dmxusb/src/org.qlcplus.QLCPlus.dmxusb.metainfo.xml
- plugins/enttecwing/src/org.qlcplus.QLCPlus.enttecwing.metainfo.xml
- plugins/hid/linux/org.qlcplus.QLCPlus.hid.metainfo.xml
- plugins/loopback/src/org.qlcplus.QLCPlus.loopback.metainfo.xml
- plugins/midi/src/org.qlcplus.QLCPlus.midi.metainfo.xml
- plugins/ola/org.qlcplus.QLCPlus.ola.metainfo.xml
- plugins/os2l/org.qlcplus.QLCPlus.os2l.metainfo.xml
- plugins/osc/org.qlcplus.QLCPlus.osc.metainfo.xml
- plugins/peperoni/unix/org.qlcplus.QLCPlus.peperoni.metainfo.xml
- plugins/spi/org.qlcplus.QLCPlus.spi.metainfo.xml
- plugins/udmx/src/org.qlcplus.QLCPlus.udmx.metainfo.xml
This tries to fix some issues reported by [AppStream Report for Debian](https://appstream.debian.org/sid/main/issues/qlcplus.html):
* **asv-url-not-secure**: use HTTPS in homepage URL of MetaInfo
* **missing-desktop-file**: define `<launchable>` tag in desktop-application MetaInfo to associate it with the .desktop file
* **metainfo-no-summary**: I guess that it would be fixed with the `<launchable>` tag since it is said that either .desktop file should have a `Comment=` field set or the component MetaInfo file should have a `summary` tag - which is the case.
> Fix some issues in AppStream MetaInfo

- resources/fixtures/Martin/Martin-MAC-401-Dual-CT.qxf
- resources/fixtures/Martin/Martin-MAC-401-Dual-RGB.qxf
- resources/fixtures/Stairville/StairVille-MH-z720.qxf
- resources/fixtures/UKing/UKing-7x10W-Mini-Moving-Head.qxf
We found 4 broken fixtures in the library and we fixed it. Generally, it was a problem with indexes and dimmer share across multiple heads.
> Fix broken fixtures

- ui/src/virtualconsole/vcbutton.cpp
This happens for example at BCF 2000 and probably also APC40 mk2 due to some kind of internal feedback.
Only thing to do was to add updateFeedback() as soon as a button on external controller is released so that it has a proper LED state and not the one given by its "internal" feedback.
The change works great at my BCF 2000, since I have no other controllers at hand maybe someone could give it a try.
Bug has been reported here: http://www.qlcplus.org/forum/viewtopic.php?f=5&t=6900&p=29106
And I tried to describe it well here: http://www.qlcplus.org/forum/viewtopic.php?f=24&t=10158&p=45921#p45916
> Fixed feedback not working with buttons on some controllers

- ui/src/app.cpp
- ui/src/app.h
When detaching a context the Qt style sheet is not applied to the new window. This is because DetachedContext does not call QMainWindow::setStyleSheet() nor set any parent where the style sheet could be inherited from.
Disclaimer: This patch is only tested on Linux (Ubuntu 20.04.2 LTS). I have no idea if setting the main window as parent might have any other unforeseen consequences. Everything seems to work as usual.
> Make detached contexts apply the Qt style sheet

- resources/rgbscripts/blinder.js
- resources/rgbscripts/rgbscripts.pro
This RGB script simulates one or multiple blinders on an RGB panel. It displays the lamp and reflector before finally lighting the while panel as a blinder light effect would do.
I hope this may this be useful when syncing blinder elements on the stage.
> Simulate a blinder on an RGB panel.

- plugins/midi/src/common/midiprotocol.cpp
- plugins/midi/test/midi_test.cpp
- plugins/midi/test/midi_test.h
VC frame pages encode their value in the channel value sent to the plugin, when using the MIDI OMNI
channel, this gets embedded in the bits which define the MIDI channel to send a feedback message on.
Take off the embedded page data to get the correct MIDI channel for sending feedback.
Add some simple test cases to validate the change.
[Forum discussion](https://www.qlcplus.org/forum/viewtopic.php?f=33&t=14709)
> Account for channel value modifed with VC widget page value when using MIDI feedback for OMNI channel.

- resources/fixtures/scripts/fixtures-tool.py
It's now possible to call the script with both `python3` and `python2` (although the latter is no longer maintained).
> Add parentheses to `print` in Python script (Python 3 compatibility)

- ui/src/addfixture.ui
- ui/src/virtualconsole/vcwidget.cpp
Once again I'm getting warnings (treated as errors) breaking compilation for Tumbleweed in OBS, so I've removed the QComboBox::AdjustToMinimumContentsLength property as it seems unnecessary (the QComboBox above it doesn't have this either), and instead added a tooltip even if the meaning of that choice should be totally clear.
The second change of 2 instances from now deprecated Qt::MidButton to Qt::MiddleButton, which seems to be around already since Qt 4.6.0.
> fix handling of two deprecated Qt5 enum value names

- engine/test/inputoutputmap/inputoutputmap_test.cpp
- engine/test/qlcfixturedefcache/qlcfixturedefcache_test.cpp
Hi, this is part one of the CPP files patches to fix problems when running the unittests in a QMLUI environment under Linux.
This patch addresses the comparison of path names, when done relatively, there is no "contains" match due to the leading "./" in the relative path that is compared.
> Use the full path for comparison to fix a test failure in the qmlui build

- engine/src/doc.cpp
- engine/src/scriptv4.cpp
- engine/src/scriptv4.h
- engine/test/doc/doc_test.cpp
Hi, this is part two of the CPP files patches to fix problems when running the unittests in a QMLUI environment under Linux.
This patch addresses the new scriptv4 "functionlist" handling which lacked the second information in the list, which is the line number. The doc.cpp failed with an index out of bound error, which is now leading to a debug message. The keywords and translation from legacy to v4 is now more explicit between the versions.
> Fix script bracket parsing and add line number to usage list.

- engine/test/script/script_test.cpp
Hello Massimo,
The original Script::executeCommand is not part of scriptv4, so the test needs to use another entry point in order to also work for scriptv4.
Nevertheless, please check the test as it does not seem to implement any useful outcome (it seeds a script with syntax errors, but does not even check the reaction on these), but at least now it compiles.
> Choose an common test entry point for script.cpp and scriptv4.cpp

- ui/src/flowlayout.cpp
This fixes #1284 - [ui] XY Pad doesn't scale correctly.
Between 4052a1b (10.06.2020) and 8e24317 (13.06.2020) the value was set
from zero to Qt::Vertical, which caused the xy pad to display incorrectly.
The original return value was zero, the enumeration is:
enum Orientation {
Horizontal = 0x1,
Vertical = 0x2
};
> Change the FlowLayout from vertical to horizontal.

- plugins/dmxusb/src/dmxinterface.cpp
- plugins/dmxusb/src/dmxinterface.h
This has been tested and works fine using port #0 on the unit i.e.
port closest to the USB connector.
> Add support for FTDI USB-COM485-PLUS2 for DMX USB Interface

- engine/src/rgbscriptscache.cpp
- engine/test/rgbscript/rgbscript_test.cpp
- engine/test/rgbscript/rgbscript_test.h
- resources/rgbscripts/alternate.js
- resources/rgbscripts/circles.js
- resources/rgbscripts/devtool.html
- resources/rgbscripts/devtool.js
- resources/rgbscripts/flyingobjects.js
- resources/rgbscripts/lines.js
- resources/rgbscripts/strobe.js
While searching through the logs for the JS execution problem and errors, I would like to add the following lines to avoid the errors while loading files which are not meant to be rgbscripts:
Do not load RGBscript files which are not script files (Makefiles, backup files, directories, etc.)
> Do not load RGBscript files which are not script files

- resources/rgbscripts/devtool.html
- resources/rgbscripts/devtool.js
Hello Massimo, I started to work again on the draft pull request for a fireworks script - to see if we can have something useful at the end of the year :-).
While at it, I saw a need to display a preview grid with smaller pixels - and potential namespace clashes between devtool and the script under development, so I modified it in the devtool:
- use devtool. namespace in devtool local storage, to avoid name clashes with parameters named width, height, size, speed, etc.
- Add a parameter to size the pixels in the preview grid and fit a larger preview grid on the screen.
> Devtool: Separate localstorage namespace, add pixel size in grid settings

- plugins/peperoni/unix/z65-peperoni.rules
- plugins/udmx/src/z65-anyma-udmx.rules
SYSFS key has been removed a long time ago from udev (in v174), and those rules generate errors that we could get rid of.
> Remove SYSFS from udev rules

- ui/src/speeddial.cpp
- ui/src/speeddial.h
The Speed Dial widget features a "Tap" button that allows users to tap along with a beat, when choosing a duration.
Currently, this tap button only computes the time since the last tap. The computed value can be off by +-20ms. When tapping to music, this is enough to put the beat completely out-of-phase with the music in 10 seconds.
This patch records the most recent 20 taps, and computes the tempo that best passes through all of them. Within 10 taps it can compute a tempo that's correct +- 2ms. It's even robust against occasional missed taps.
The first tap uses the old (current) behavior, as does waiting more than 1.5 seconds in between a tap.
> Improve the tempo detection algorithm

- plugins/velleman/src/velleman_mock.cpp
File `plugins/velleman/src/velleman_mock.cpp` included the header file `stdint.h` (used for data type `int32_t` in this case) only if `WIN32` or `Q_OS_WIN` was defined. This is perfectly fine for most Linux and macOS systems. However, it can fail if another libc-implementation other than glibc is used.
For [musl libc](https://musl.libc.org/) on Gentoo Linux, the build fails since `int32_t` is not defined: https://bugs.gentoo.org/830558
This PR fixes the problem by including `stdint.h` in any case. This still compiles fine with glibc on Gentoo Linux and is probably more correct anyways.
I honestly didn't to much testing since I don't have a velleman device but since the compilation worked fine and the PR doesn't touch any logic, I wouldn't expect any runtime problems.
> velleman_mock: Include stdint.h in any case since it's required by more than just Windows (musl for example)

- ui/src/virtualconsole/vccuelist.cpp
The vccuelist feedback (Side Fader) works fine in Crossfade-Mode but in Steps-Mode the feedback values goes crazy.
> ui: fix wrong feedback on vccuelist in stepmode

- webaccess/res/keypad.html
- webaccess/res/simpledesk.js
- webaccess/res/websocket.js
This PR implements an automatic reconnection when the websocket is closed.
When using the webaccess in iOS Safari everytime that the iPhone screen is locked the websocket connection is lost and to workaround that, we are forced to refresh the page.
> chore: add websocket reconnect when connection is closed

- plugins/midi/src/alsa/alsamidioutputdevice.cpp
- plugins/midi/src/common/midiprotocol.h
When using MIDI plugin in Note mode to output channel data from QLC, notes are sent twice.
This patch removes a superfluous call of snd_seq_event_output(m_alsa, &ev); that causes this misbehaviour.
> avoid sending duplicate MIDI notes

- engine/test/rgbscript/rgbscript_test.cpp
- resources/rgbscripts/alternate.js
- resources/rgbscripts/balls.js
- resources/rgbscripts/ballscolors.js
- resources/rgbscripts/circles.js
- resources/rgbscripts/devtool.html
- resources/rgbscripts/devtool.js
- resources/rgbscripts/fireworks.js
- resources/rgbscripts/flyingobjects.js
- resources/rgbscripts/lines.js
- resources/rgbscripts/randomcolumn.js
- resources/rgbscripts/randomrow.js
- resources/rgbscripts/randomsingle.js
- resources/rgbscripts/snowbubbles.js
- resources/rgbscripts/squares.js
- resources/rgbscripts/starfield.js
- resources/rgbscripts/waves.js
Hello @mcallegari,
I took some in-depth time to review the attributes, usage and code of the RGB matrix scripts and have corrected the places which raised my attention. Please review if you agree with my findings.
- Set the acceptColors to a value as used in the script. Some scripts had no value set, which defaults to 2, but never used the second color.
- Set the acceptColors to 1 if the second color can neither be used in matrix object initalization and if the script does not evaluate the current progStep to always apply the same color in the same point in sequence of steps (i.e. it does not distinguish between forward / backward increments / decrements). Color change on the stage must be managed otherwise, e.g. through the virtual console to achieve a synchronous color change.
- Set the …
> Rgbscrips fix acceptColors attributes, formatting, removing unused variables

- engine/src/fadechannel.cpp
- engine/src/keypadparser.cpp
This fixes #1344. Tests on arm64 and i386 pass with this patch as we can see in [Debian buildd status](https://buildd.debian.org/status/package.php?p=qlcplus) with version 4.12.5-2.
> Round values explicitly in FadeChannel and KeyPadParser

- engine/src/script.cpp
Hello Massimo,
Here is a very simple fix for [#1270](https://github.com/mcallegari/qlcplus/pull/1270) and[ #1339](https://github.com/mcallegari/qlcplus/issues/1339) 
Replacing start() by startDetached() enables to immediately delete the QProcess object, and clean-up all associated pipes and file descriptors, without killing the running process.
This fix has been validated:
- on Linux Raspbian 10 with Qt 5.11.3
- and on Windows 10 with Qt 5.15.3
This fix does not drastically change the current behavior of system commands, unlike the fix on procfix which requires to specify a timeout (wait time) for every command. 
This fix is based on following doc & source code of QProcess::startDetached :
- https://www.qt.io/blog/2017/08/25/a-new-qprocessstartdetached
- …
> Engine - script - startDetached() enables to delete QProcess object without killing running process

- resources/fixtures/Vari-Lite/Vari-Lite-VL4000-Spot.qxf
This is the first fixture definition I'm attempting to add, I'm happy to fix any functional or quality problems with it. It follows the official DMX tables for the fixture, minus the color wheel "mid-positions" (between two colors) which aren't described by the tables, but which were also used by the other Vari-Lite fixtures.
> Add Vari-Lite VL4000 Spot fixture definition

- resources/fixtures/scripts/fixtures-tool.py
@mcallegari, under Python 3.x, the xmlFile.write function requires the .decode('utf8') to be set, under 2.7, it is not supported. The lxml.etree documentation was not explicit but threw an error due to the UTF-8 encoding, which indicated in forums that this "decode" extension would return the same results as the 2.7 output, including the file encoding.
> Fixtures tool - support --map with python 2.7

- plugins/osc/osccontroller.cpp
This fixes OSC broadcast reception on Linux as discussed here: https://www.qlcplus.org/forum/viewtopic.php?f=12&t=15647
Reception and Transmission of OSC packages tested using wireshark.
> OSC: Bind to QHostAddress::Any instead of the IP of the interface

- ui/src/showmanager/audioitem.cpp
See this forum [thread]:(https://www.qlcplus.org/forum/viewtopic.php?f=22&t=15924)
This fixes the waveform display at new file load, for me.
> update audio preview when a different file is loaded

- variables.pri
- webaccess/src/qhttpserver/http_parser.c
During analysis of the build, one warning was detected: The `-Werror` flag was set only on C++ files, not on C files.
This patch adds the `-Werror` flag also on C files and adds a compiler hint on the one occasion where the switch-case fallthrough is intentional.
> Enable Werror on C files and add compiler hint where needed

- qmlui/virtualconsole/vccuelist.cpp
Added missing saveXMLInputControl call for Side Fader external input configuration
> Save side-fader-input to qxw files

- .github/workflows/build.yml
- unittest.sh
This patch fixes the window rendering tests.
- Move tests before install targets
- Enforce QT_QPA_PLATFORM=minimal
- Let the tests evaluate the extra environment variable
Note that this is just one way to make it work. Alternatively, there could be a solution in finding and installing some missing library or library version that causes QT to being unable to render the screens during tests.
> Gh action fix

- resources/inputprofiles/Akai-APCMini-mk2.qxi
- resources/miditemplates/APCminiMK2.qxm
Color feedback values can be found here:
https://www.qlcplus.org/forum/viewtopic.php?f=30&t=16203
Some things to keep in mind:
* The output MIDI channel must be set to 7 to get 100% brightness (when MIDI channel 1 is chosen, you'll only get 10% brightness)
* The control buttons on the side however (Volume, Pan, etc.) have single LEDs which unfortunately only react to messages on MIDI channel 1. Maybe we could add a FixedMidiChannel attribute on the Feedbacks element that could be configured to overwrite the output MIDI channel used for feedback to allow 1 profile can output to multiple MIDI channels?
> Add support for AKAI APC Mini mk2

- resources/fixtures/Pro-Lights/Pro-Lights-CromoSpot300.qxf
hi, yesterday i have use that light and i had have found an error on Person1 Mode : two channels are inverted
Now is ok
> error on a fixture : Prolights cromospot 300 

- engine/src/rgbscript.cpp
- engine/src/rgbscript.h
- engine/src/rgbscriptv4.cpp
- engine/src/rgbscriptv4.h
Introduce error evaluation on the QJSEngine::call calls, to detect dynamic script errors during code interpretation (::call --> undefined indices etc.).
The error detection during evaluate() only detects static error classes while loading the scripts (::evaluate --> parse errors, missing brackets etc.).
> Introduce error evaluation on the QJSEngine::call calls

- resources/rgbscripts/marquee.js
With this pull request, I would like to correct some problems in marquee.js:
- Changing / Fading colors (color 1 / rgb) were not taken over into the background feature
- The integer in properties "16" + "3" + 1 were interpreted as string (1631) - added parseInt to ensure it is handled as a number
- The edges of the marquee were set twice, each edge had it's own way to start over. This leads to each edge having a potentially inconsistent marquee pattern (see screenshot).
- The selected marquee color is not applied but added (merged) with the background color. This significantly reduces the reachable color space for the marquee. It could be made an option (@sandinak, what's your opinion on this?), but if the user needs merged colors on the marquee, he could select the marquee merged color …
> Fix off-by-one errors and integer interpretation errors.

- resources/docs/html_en_EN/rgbscriptapi.html
Because the path of this file was changed, the link led nowhere.
> fixed broken link

- webaccess/res/virtualconsole.css
Some improvements to button widgets in the web view:
- Hide the overflow of text in vcbuttons when the button name does not fit.
- Center the text vertically and horizontally to match the layout in Qt.
- Include the borders in the button width/height to avoid shifting the layout and hiding parts of other widgets.
(Tested in Firefox and Chromium, should work anywhere.)
Attached below are screenshots of some test widgets in the Virtual Console and in Webaccess.
> webaccess: improve vcbutton overflow and alignment

- unittest_cmake.sh
#1408 
@mcallegari 
- I am not so clear how `engine/test/qlci18n` works.
Because `qlci18n_fi_FI.ts_` is required for testing `qlci18n` and `qlci18n_fi_FI.ts` is required for compiling the target and now both are omitted from Git.
Tested on my side and it looks like working when I manually added these 2 files.
- It looks like `make check` for Windows is missing in the todo list. Don't we need it anymore? It looks like that it was there in the original "qlc.pro" file.
- I manually modified the 1st line of `resources/fixtures/scripts/fixtures-tool.py` from `#!/usr/bin/env python` to `#!/usr/bin/env python3`, otherwise it did not work. Not sure if python3 is default in your develop environment.
> Added missing unittest_cmake.sh

- create-appimage-cmake.sh
- engine/CMakeLists.txt
- platforms/linux/CMakeLists.txt
- platforms/windows/CMakeLists.txt
- qmake2cmake.md
#1408 
@mcallegari I was able to make AppImage using both of debian and official QT packages.
It could run with no issue when I built AppImage with the official QT package.
But it showed a white blank screen when I built with the debian QT package.
I checked the original qmake files and it looked like we never built AppImage with the debian QT packages.
So I am opening this PR and hope you can review it.
Thanks.
PS: I made a small modification on Windows deployment, and I believe it has no issue to merge.
> Bugfix on AppImage.

- plugins/dmxusb/src/enttecdmxusbpro.cpp
- plugins/dmxusb/src/nanodmx.cpp
- plugins/dmxusb/src/stageprofi.cpp
For any value over 127, the nanodmx code sends the update to the device repeatedly rather than just once, as happens for any value <= 127
This is caused by a signed/unsigned value comparison in nanodmx.cpp
Fixed and tested. Also fixed the same code in stageprofi.cpp and enttecdmxusbpro.cpp, but not tested.
> NanoDMX/StageProfi/Enttec fix 

- engine/src/chaserrunner.cpp
Instead of using the random order of a chaser, the chaserrunner sets the step index to zero when started by a virtual console button. Fixed by using the randomStepIndex method instead of just setting the index.
> Fix random order chaser always starts with first step

- qmlui/virtualconsole/vcbutton.cpp
- ui/src/virtualconsole/vcbutton.cpp
- ui/src/virtualconsole/vcbutton.h
As described in the forum post the copying of the buttons was not implemented correctly.
I added the copying of the options to the copyfrom method.
> Override flash functionality: Fix options not copied when copying buttons

- resources/rgbscripts/devtool.html
- resources/rgbscripts/devtool/devtool.js
Added color pickers next to the color input fields and fixed a problem, where all preceding zeros in the hex color value would be removed on reload.
> Color Picker & Padding

- resources/fixtures/Eurolite/Eurolite-LED-PLL-480-CW-WW.qxf
- resources/fixtures/FixturesMap.xml
Add Eurolite LED PLL-480 CW/WW [1]. The names and description were taken from 40001895-Manual-119588-1.000-de_en.pdf [2]. This fixture definition has some shortcomings:
1. There is no type for floodlights, so ColorChanger is used.
2. There are no separate presets for warm and cold white. So both warm and cold white have to use the same preset.
3. The bulb colour temperature field does not allow specifying the color range 3200K - 5600K. So the lower warm white colour is specified.
[1] https://www.steinigke.de/en/mpn40001895-eurolite-led-pll-480-cw-ww-panel.html
[2] https://www.steinigke.de/download/40001895-Manual-119588-1.000-eurolite-led-pll-480-cw-ww-panel-de_en.pdf
> resources: add Eurolite LED PLL-480 CW/WW

- qmlui/virtualconsole/vccuelist.cpp
- ui/src/virtualconsole/vccuelist.cpp
Adjust CueList slider value calculation to fully align ValueChanged->Step# and Step#Changed->Value calculations.
Previously, clicking the PreviousStep button didn't always update the slider position, due to off-by-one issues          near whole-numbered calculated values.  Example: with a 6-step chaser, advance to the end, then click the Previous Cue button and note that the slider only jumps up every other click. Also, if you move the slider position with keystrokes up and down (or presumably also via a midi encoder wheel up/down), note that it jumps to the next step at slightly different values than the ones that are calculated when using next/previous step buttons -- and then the displayed value at the top of the slider "jumps" to the top end of the subset of values calculated to …
> Cuelist slider fix

- qmlui/qml/virtualconsole/VCButtonItem.qml
- ui/src/virtualconsole/vcbutton.cpp
As suggested by mcallegari in the forum discussion about the overriding flash functionality, I changed the visualization of the flash button to display the border red instead of green when FlashForceLTP or OverridePriority is used.
> Flash override: Change button border to red when button uses override functions.

- qmlui/js/TimeUtils.js
- qmlui/qml/KeyPad.qml
- qmlui/qml/TimeEditTool.qml
As described in forum thread https://www.qlcplus.org/forum/viewtopic.php?p=71374, I added the linear regression method used in QLC+ 4 to the BPM tapping functionality of QLC+ 5.
> QLC+ 5: Add linear regression to BPM tapping

- resources/fixtures/FixturesMap.xml
- resources/fixtures/Showtec/Showtec-LED-Par-64-Short-V2.qxf
Add fixture definition for the Showtec LED Par 64 Short V2
> resources: Add fixture definition for Showtec LED Par 64 Short V2

- README.md
Fix: Opening paragraph typos
Add: Better link for GitHub Latest Release badge
Add: Supported protocols banners
Add: Help wanted section
Chore: Condense "Developers at work" section
Fix: Use sentence case for headings [https://www.ed.ac.uk/editorial-style/formatting/headings](https://www.ed.ac.uk/editorial-style/formatting/headings)
Add: GitHub contributor profile images
> Another set of readme Improvements

- resources/fixtures/Cameo/Cameo-P2-FC.qxf
The Cameo P2 FC has 12 different modes.
This patch adds support for 7 of them, which don't depend on the device setting channel.
> fixtures: Add Cameo P2 FC

- resources/docs/html_en_EN/supported-input-devices.html
- resources/inputprofiles/Worlde-Easypad.12.qxi
The Worlde Easypad.12 is a relatively cheap MIDI pad, that can be used as MIDI input. All controls that standard MIDI messages are supported here.
However, there are a few missing features:
* The slider sends SYSEX commands
* The bank button sends SYSEX commands
* Unclear how to set LED color. (using the feedback mechanism did not change anything)
I created this profile six years ago and forgot about it.
When I recently stumbled over the pad, I wanted to add support but found the old profile in my `.qlcplus` folder.
Enough reason to create a PR and see if it will be accepted.
> inputprofiles: Adding Worlde Easypad.12 MIDI pad

- ui/src/virtualconsole/vcxypad.cpp
In v4, the VCXYPad did not copy the presets. This patch completes the copy action by adding the presets in createCopy.
Sample workspace for testing the copy action:
[VCXYPad.qxw.zip](https://github.com/mcallegari/qlcplus/files/14780777/VCXYPad.qxw.zip)
> Copy VCXYPad presets (v4)

- qmlui/fixturemanager.cpp
Fix for issue #1542 . 
fxAddress is 0 based (0-511). If the requested address is 511 and the unit has 1 channel, it should fit. In this case, (fxAddress = 511) + (channels = 1) == (UNIVERSE_SIZE = 512) => Should be ok. 
Simply need to remove the "=" to fix the issue.
Easy fix for a first timer! Was fun to figure my way around. ;)
> Fix fixture patch address verification

- engine/audio/src/CMakeLists.txt
- hotplugmonitor/src/CMakeLists.txt
Building qlcplus (upstream/master) with GCC 13.2.1 (Fedora 39) triggers build errors when using the following commands:
```
mkdir build
cd build
cmake ..
make
```
The first error is:
```
[...]
[ 10%] Linking CXX shared library libqlcplusengine.so
/usr/bin/ld: ../audio/src/libqlcplusaudio.a(audio.cpp.o): relocation R_X86_64_32 against symbol `_ZTV5Audio' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: failed to set dynamic section sizes: bad value
collect2: error: ld returned 1 exit status
```
The second error is:
```
[...]
[ 46%] Linking CXX shared library libqlcplusengine.so
/usr/bin/ld: ../../hotplugmonitor/src/libhotplugmonitor.a(hotplugmonitor.cpp.o): relocation R_X86_64_32 against symbol `_ZTV14HotPlugMonitor' can not be used when making a shared …
```
> Fix build/linker issues with recent GCC releases and static libraries

- qmlui/qml/ActionsMenu.qml
- qmlui/qml/BeatGeneratorsPanel.qml
- qmlui/qml/KeyPad.qml
- qmlui/qml/MainView.qml
- qmlui/qml/UISettingsEditor.qml
- qmlui/qml/popup/PopupAbout.qml
Fix general UI scaling bugs including
- Top bar elements drift downwards when scale goes under 1.0
- Background for "Actions" bar didn't automatically adjust to rescaled sizing (required second click on "Actions" menu item)
- Prevent BPM "ratchet" issues where scaling up increases keypad button height, but scaling down leaves it at the maximum height scaled to
- Beat Indicator / Stop all button not scaling with UI
- interface jitter in UI Setting editor
- Width of text elements in UI settings editor, but font size changes
- Undo/Redo buttons to layout to scale properly
- Prevent text overflow in about dialog
Current (Beat generator panel has been scaled up, then returned to smaller size):
Pull Request:
> UI scaling improvements

- qmlui/qml/QLCPlusKnob.qml
- qmlui/qml/fixturesfunctions/PresetCapabilityItem.qml
- qmlui/qml/virtualconsole/VCSliderItem.qml
- qmlui/virtualconsole/vcslider.cpp
- ui/src/clickandgowidget.cpp
- ui/src/clickandgowidget.h
- ui/src/virtualconsole/vcslider.cpp
Originally, I came from the v4 issue that having a gobo knot which is limited to values for static gobos only did not select the correct gobo values when clicking on the CnG Gobo entry.
Please find attached the simple workspace showing an example setup:
"Midi" input (simulated on an Artnet universe) --> Range- limited knob --> Fixture
[gobo-vc.qxw.txt](https://github.com/mcallegari/qlcplus/files/14746163/gobo-vc.qxw.txt)
Along the way when also trying the example in v5, I cam across a few otherv5  knob / slider  limitations which are fixed in this patch:
- Gobo images were not shown
- VCslider limits were not respected when attaching to an Input Event (e.g. Midi)
- Mouse Wheel inputs were not yet supported for the vcKnob
- only the youngest knob or fader was able to modify a LTP channel …
> VC Click & Go Gobo control on limited-range knobs and sliders

- qmlui/qml/ColorToolFull.qml
This PR fixes a bug where using the "Full" color picker mode doesn't update the color of fixtures or UI color settings.
> Fix color picker full mode

- engine/src/chaser.cpp
- engine/src/chaser.h
- qmlui/virtualconsole/vccuelist.cpp
- qmlui/virtualconsole/vccuelist.h
- Currently adding or removing a widget is not reflected in the cue list widget unless the project is saved and reopened 
- Also apparent cause of crash at https://www.qlcplus.org/forum/viewtopic.php?t=17147, as the cue list would attempt to access a non-existent index
- This PR reloads the chaser cue list if a function is added or removed from the linked chaser, allowing updates to be seen in real time and preventing the crash
> Refresh Cue List Widget on Addition or Removal of a Step from Chaser

- qmlui/qml/GenericMultiDragItem.qml
- qmlui/qml/TreeNodeDelegate.qml
- qmlui/qml/fixturesfunctions/FixtureNodeDelegate.qml
- qmlui/qml/fixturesfunctions/LeftPanel.qml
- qmlui/treemodel.cpp
Bugs fixed:
- selecting or deselecting a fixture with Fixture Groups panel open results in a segfault
- Escape erases the names of fixtures and universes
- Switching from Fixture Groups view to another view in the left panel and then switching back to fixture view does not clear filter until the search button is clicked again, without any visual indication that a filter is still active
> Fix bugs in Fixture Search

- plugins/hid/HID_ca_ES.ts
- plugins/hid/HID_cz_CZ.ts
- plugins/hid/HID_de_DE.ts
- plugins/hid/HID_es_ES.ts
- plugins/hid/HID_fi_FI.ts
- plugins/hid/HID_fr_FR.ts
- plugins/hid/HID_it_IT.ts
- plugins/hid/HID_ja_JP.ts
- plugins/hid/HID_nl_NL.ts
- plugins/hid/HID_pt_BR.ts
- plugins/hid/configurehid.cpp
- plugins/hid/configurehid.h
- plugins/hid/configurehid.ui
- plugins/hid/hiddevice.cpp
- plugins/hid/hiddevice.h
- plugins/hid/hiddmxdevice.cpp
- plugins/hid/hiddmxdevice.h
- resources/docs/html_en_EN/hidplugin.html
Adding the ability to set the DE/FX5/Nodle devices into merger mode as explained in the updated docs.
Tested with two Nodle R4S.
> Add merger mode for HIDDMXDevices (DE/FX5/Nodle)

- plugins/hid/hidjsdevice.cpp
- plugins/hid/hidplugin.cpp
Hi,
this is a proposal for a more detailed and more robust naming of HID devices.
It covers:
1. HIDDMXDevices always have a serial number, thus it is appended in parenthesis to be able to distinguish several connected devices.
2. Those HIDJSDevices that expose a serial number append it in parenthesis as well.
3. HIDJSDevices not exposing _any_ product or manufacturer name use VID:PID as a naming scheme instead. (Previously those had a completely empty name.)
I'm open to changes of course.
> Proposal of a rework of HID device names

- ui/src/addfixture.cpp
No forum post as this is a very small change.
When you want to add a fixture, you first search for the fixture, not rename the default dimmer option.
This pull request automatically brings the cursor to the search bar, so the user can immediately begin searching for the fixture they wish to add.
> Fix: Highlight the searchbar when first opening the addfixture dialogue.

- resources/fixtures/Martin/Martin-MAC-Axiom-Hybrid.qxf
1. Gobo references have been added (Closest ones I could find in the library)
2. Colour wheel has been updated with the default colours shipped with the fixture
3. Channel presets have been fixed to allow 2D view to work
The gobos are by no means a 1:1 representation of the fixture. If needed, I can create new SVGs. 
For reference, here is the manual: https://www.martin.com/en/site_elements/martin-mac-axiom-hybrid-user-manual
> Fix - Martin MAC Axiom Hybrid fixture definition

- ui/src/fixtureselection.cpp
Forum thread: https://www.qlcplus.org/forum/viewtopic.php?t=17674
This pull request is made in response to the above forum thread. When adding a fixture, it can be helpful to have the address available for reference. 
Testing required:
- EFX Editor
- Scene Editor
> Add channel address in add fixture dialogue

- CMakeLists.txt
- qmlui/qml/popup/CustomPopupDialog.qml
- qmlui/qml/popup/PopupDisclaimer.qml
Add a compile option to build for QLC5.
Remove qml slot depreciation.
Adapt disclaimer text size to content.
> Build option+ui fix

- qmlui/fixturemanager.cpp
- qmlui/fixturemanager.h
Fix endless loop on Universe view : Getters should not emit change if not changed.
> (Qt6) Fix endless loop on Universe view

- hotplugmonitor/src/CMakeLists.txt
hotplugmonitor is not hooked up to be installed as dynamic library, and hotplugmonitor/src/src.pro declares it as staticlib . It seems like it was the intent that the cmake build system should do the same.
> cmake: Make hotplugmonitor a static lib

- qmlui/fixtureutils.cpp
- Currently, activating 3d mode with fixtures that have the same value for minimum and maximum for RotationStop (for example the Robe ColorSpot 250 AT) will cause the application to crash due to division by 0
- This PR skips the calculation (which is never actually used in RotationStop capabilities) to prevent the application crash
Initial Forum Report: https://www.qlcplus.org/forum/viewtopic.php?p=74082
> Prevent crash with rotation stop capability on some fixtures

- ui/src/virtualconsole/virtualconsole.cpp
- ui/src/virtualconsole/virtualconsole.h
With our Windows QLC setup we noticed you can get QLC+ 4 (Qt5 UI) to crash easily on Windows by following these steps:
- Open QLC+4
- Add any type of slider to the virtual console (slider/knob)
- Press any of the accent keys on a german QWERTZ or french AZERTY keyboard (^, ` or ´) twice
--> Program crashes
This usually happens accidentally because the caret symbol is right next to the escape key on the top left.
I just now compiled QLC+ from master for Windows MINGW64 with MSYS2 Qt5 debug libraries (v5.15.15-1) and got this stack trace after following the steps to reproduce the crash:
```gdb
Thread 1 received signal SIGSEGV, Segmentation fault.
QWidget::setStyleSheet (this=0x0, styleSheet=...)
at C:/M/B/src/qtbase/src/widgets/kernel/qwidget.cpp:2540
warning: 2540 …
```
> Windows Qt UI: Fix segfault when pressing accent keys (^, `, ´) on german QWERTZ keyboard in VCSlider

- resources/rgbscripts/ballscolors.js
When setting the number to e.g. 15, the index overran.
> Fix out-of-bounds error when selecting too many balls.

- engine/src/universe.cpp
- engine/test/universe/universe_test.cpp
A friend of mine noticed that whenever he executed a relative EFX on 16-bit PAN/TILT which goes out of range (e.g. a circle with radius 10 at PAN offset 5), the PAN/TILT faders jump to the respective other end of the range.
This seems to be a regression introduced with the 16bitfade branch, since in version 4.12.7, the values are still being clamped.
This commit fixes this issue and adds related tests.
> universe: clamp 16-bit values in writeRelative

- plugins/artnet/src/ArtNet_de_DE.ts
- plugins/dmxusb/src/DMX_USB_de_DE.ts
- plugins/gpio/GPIO_de_DE.ts
- plugins/midi/src/MIDI_de_DE.ts
- plugins/osc/OSC_de_DE.ts
- qmlui/qlcplus_de_DE.ts
- ui/src/qlcplus_de_DE.ts
Added translations for the new strings introduced yesterday via e0286a0b0a4e9be9c8308e6a84be0bff79aa6fd6 and fixed some typos.
@kripton Feel free to correct me and comment on my changes.
> translations: update German (again)

- .github/workflows/build.yml
`-S` for the source dir and `-B` for the build dir. Also uses `-DCMAKE_BUILD_TYPE` instead of `sed` to set the build type
> Github actions: Use cmake -S . -B build to simplify file

- ui/src/fixturegroupeditor.cpp
- ui/src/fixturegroupeditor.h
- ui/src/fixturegroupeditor.ui
This pull request enhances the Fixture Group Editor in QLC+ by adding "Up" and "Left" buttons. These buttons allow users to add fixtures to a group starting from the selected cell in the reverse directions (upwards and leftwards) of the existing "Right" and "Down" buttons.
1. Added new slots: slotUpClicked() and slotLeftClicked().
2. Extended addFixtureHeads() to handle Qt::UpArrow and Qt::LeftArrow.
4. Added "Left" and "Up" buttons to the layout in fixturegroupeditor.ui.
5. Configured the buttons with an appropriate tooltip and icon (:/back.png, :/up.png).
6. Connected the buttons to slots in the constructor of FixtureGroupEditor.
I have verified the functionality of "Up" and "Left" buttons across various scenarios, ensuring correct behaviour and bounds handling.
> Add missing "Up" and "Left" Buttons to Fixture Group Editor

- variables.pri
- webaccess/res/virtualconsole.js
- webaccess/src/webaccess.cpp
Instead of the untranslated "Page: %1", the web virtual console now displays the page names that were set in the local QLC+ virtual console.
"Page: %1" is now only used as a backup and can be translated.
This PR also fixes a bug where it was not possible to change the page of a frame via the web interface.
To reproduce this issue, the frame name needs to contain a `"` or end on a `\`, as these strings were not escaped before being inserted into the JavaScript code.
> webaccess: show page names of multi-page (solo-) frames

- resources/fixtures/beamZ/beamZ-MHL75-Hybrid-Moving-Head.qxf
Add beamZ MHL75 Hybrid Moving Head fixture
Created and verified to be working with the given fixture
> Add beamZ MHL75 Hybrid Moving Head fixture definition

- ui/src/virtualconsole/vcmatrixcontrol.cpp
Implement backward-compatibility for loading VC animation widgets with knobs.
I noticed that qxw files created in previous versions would lose the VC animation knobs and their settings and show color buttons instead. This fixes it for v4. It seems not yet implemented in V5/qml (which prints already "Control" attribute not found / parsed).
> Backward-compatibility for loading QXW files with color knobs

- debian/changelog
- resources/fixtures/Briteq/Briteq-BT-Theatre-250EZ-Mk3.qxf
- resources/fixtures/Briteq/Briteq-BT-Theatre-250EZ.qxf
- resources/fixtures/FixturesMap.xml
This commits adds the following fixture descriptions:
* Briteq BT Theatre 250EZ and Briteq BT Theatre 250EZ Mk2
* Briteq BT Theatre 250EZ Mk3
The 250EZ and the 250EZ Mk2 have the same channel layout. To avoid duplication, there is only one fixture description file for them.
Vendor information:
* https://briteq-lighting.com/de/bt-theatre-250ez
* https://briteq-lighting.com/de/bt-theatre-250ez-mk2
* https://briteq-lighting.com/de/bt-theatre-250ez-mk3
> resources: Add Briteq BT Theatre 250EZ

- .github/workflows/build.yml
- platforms/linux/qlcplus-fixtureeditor.desktop
- platforms/linux/qlcplus.desktop
When searching for QLC+ in my app launcher, I think to search for "QLC+", not "Q Light Controller Plus".
This change also makes it consistent with the name of the fixture editor desktop entry, which is "QLC+ Fixture Editor".
> Rename Linux desktop file to be consistent

- plugins/E1.31/e131controller.h
A compile error was observed on Fedora Rawhide (see #1709), which showed a few missing includes.
This was likely caused by some changes in a recent QT release.
Fixes #1709
> e131controller.h: Fix QT includes

- ui/src/virtualconsole/vcproperties.cpp
- ui/src/virtualconsole/vcproperties.h
- ui/src/virtualconsole/vcpropertieseditor.cpp
- ui/src/virtualconsole/virtualconsole.cpp
- webaccess/src/webaccess.cpp
The slider mode is stored in the XML file, but is not refreshed when a document is loaded (or a new document is created). This PR fixes that.
> Refresh Grand Master slider mode on new/load document

- create-dmg-cmake.sh
macOS: set minimum OS version to 10.13 (Qt5) or 12.0 (Qt6)
Without this setting the target macOS version is the version of the host system
So compiling QLC on macOS 15 will stop application from running on earlier macOS systems
**Current 4.14.1 Intel release is not runnable on macOS 11 or earlier
Current 4.14.1 Apple Silicon release is not runnable on macOS 14 or earlier**
Although there is a workaround still: user has to run the binary from terminal specifying
/Applications/QLC+.app/Contents/MacOS/qlcplus
This is not very nice, so this commit fixes it.
Tested with xcode 13.4.1 on Intel macOS 12 Monterey. Qt 6.9:
otool -l ~/QLC+.app/Contents/MacOS/qlcplus | grep -C4 LC_BUILD_VERSION
minos 12.0
sdk 12.3
Verified to run on Intel macOS 12 Monterey
Qt 5.15:
otool -l …
> macOS: set minimum OS version to 10.13 (Qt5) or 12.0 (Qt6)

- engine/src/doc.cpp
- engine/src/inputoutputmap.cpp
- engine/src/inputoutputmap.h
- engine/src/qlcinputprofile.cpp
- engine/src/qlcmodifierscache.cpp
- engine/src/qlcmodifierscache.h
as reported by address sanitizer
Direct leak of 1200 byte(s) in 15 object(s) allocated from:
#0 0x7f16cdef5778 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
#1 0x7f16cca921da in QLCModifiersCache::load(QDir const&, bool) engine/src/qlcmodifierscache.cpp:86
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7f16cdef5778 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
#1 0x7f16cc801e73 in Doc::Doc(QObject*, int) engine/src/doc.cpp:70
Indirect leak of 291744 byte(s) in 4052 object(s) allocated from:
#0 0x7f16cdef5778 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
#1 0x7f16cca7ac52 in QLCInputProfile::loadXML(QXmlStreamReader&) …
> engine: fix 3 memory leaks

- ui/src/virtualconsole/vcsliderproperties.cpp
- ui/src/virtualconsole/vcsliderproperties.ui
This was a feature request in [the forum](
https://forum.qlcplus.org/viewtopic.php?t=18266).
> The QTreeWidget for Slider dialog → Level tab now allows sorting

- plugins/gpio/gpioplugin.cpp
I use Podman+QEmu to test my Raspberry Pi QLC+ images on my development machine. It's a much faster development cycle. But there are no GPIO chips on my development machine, and the Raspberry Pi QLC+ image obviously has that plugin enabled. Previously I resorted to a hacky "delete GPIO plugin when running inside QEmu"-script, but this PR ensures that the situation is handled gracefully.
For anyone interested in running the Raspberry Pi QLC+ image on a non-arm64 Debian machine, the global steps are:
- `sudo apt install podman qemu-user-static`
- Extract rootfs from QLC+ `.img` file to `somedir/root`
- `sudo podman run -it --rootfs somedir/root bash`
> Handle the case when `make_chip_iter()` throws exception

- engine/src/cue.cpp
- engine/src/cue.h
- engine/src/cuestack.cpp
- engine/src/fixture.cpp
- engine/src/fixture.h
- engine/src/rgbmatrix.cpp
- engine/src/rgbmatrix.h
- engine/test/cue/cue_test.cpp
- ui/src/simpledeskengine.cpp
- ui/src/simpledeskengine.h
- ui/src/virtualconsole/vcmatrix.cpp
- ui/src/virtualconsole/vcmatrix.h
- ui/src/virtualconsole/vcmatrixcontrol.cpp
- ui/src/virtualconsole/vcmatrixcontrol.h
- ui/src/virtualconsole/vcmatrixpresetselection.cpp
- ui/src/virtualconsole/vcmatrixpresetselection.h
- ui/src/virtualconsole/vcmatrixproperties.cpp
- webaccess/src/webaccess.cpp
Use QMap instead of QHash while saving XML. This way the tags in the resulting XML are always in the same order. When storing XML files in a version control system such as Git, this circumvents false differences between revisions.
> Save XML tags in determinicstic order (better when using a VCS)

- resources/fixtures/FixturesMap.xml
- resources/fixtures/Stairville/Stairville-SonicPulse-LED-Bar-10.qxf
This fixes the warning `bool
QLCFixtureDefCache::addFixtureDef(QLCFixtureDef*) Cache already contains "Stairville SonicPulse LED Bar 05"` and also shows the SonicPulse LED Bar 10 in the fixtures list when adding a fixture.
The fixture in question is [this one](https://www.thomann.de/intl/stairville_sonicpulse_led_bar_10.htm).
> Correctly name 'SonicPulse LED Bar 10'

- ui/src/virtualconsole/vcxypadarea.cpp
This was first reported [in the forum](https://forum.qlcplus.org/viewtopic.php?t=18302).
> Prevent NPE with setEFXInterval(uint) after 'stop all functions' is hit

- ui/src/rgbmatrixeditor.cpp
During the "RGB Matrix to sequence" logic, while looping through the RGB Matrix, everything is ok. But the last step of the loop will try to set `currentStep` to a value that is 1 too high. This will in turn cause QLC+ to try to set colors to values out of range 0 <= c < 256, causing errors in the console.
> Do not updateStepColor() with 1-too-high step count

- ui/src/addrgbpanel.cpp
- ui/src/addrgbpanel.h
We now include the 16bit checkbox in the calculation of the maximum amount of columns.
We also set the value of m_columnSpin to the maximum if its current value is over the new maximum.
> Update m_columnSpin when m_compCombo or m_16bitCheck change

- engine/src/rgbmatrix.cpp
- resources/rgbscripts/balls.js
- resources/rgbscripts/plasma.js
This fixes the bug described in [this forum post](https://forum.qlcplus.org/viewtopic.php?p=77014) and also shown in [this video](https://github.com/user-attachments/assets/7f285c81-3cca-45e0-b95d-f70229de19e4). This PR supersedes #1697 with a better fix.
To be honest, I do not fully understand why the code was there. And because of that, I do not fully understand what I might have broken by removing the lines. It code block _seems_ illogical in that place, and it fixes the issue, but more testing should be done before merging I think... Only... What to test and how to test? 😀 I tested with `Plasma` (where the issue surfaced), `Balls` and `Even/odd` (which doesn't use the new 5-color-max feature). I did not notice something breaking.
> Remember colors that are set on RGB matrix

- ui/src/speeddial.cpp
If you do, dialogs (Save As, QColorPicker, etc) do not show anymore. Probably the main event loop is "a little busy" with the timer.
To reproduce:
- build using Qt5,
- add SpeedDial widget (default value is 0ms, leave it at that)
- save workspace
- load workspace (causing VCSpeedDial::loadXML(QXmlStreamReader &root) → SpeedDial::setValue(int ms, bool emitValue) →
SpeedDial::updateTapTimer()
- try to open a Save As dialog or a color picker
> Starting m_tapTickTimer with a 0ms interval makes for a busy-wait loop

- ui/src/virtualconsole/vcxypad.cpp
**Steps to Reproduce:**
1. Open QLC+ and add a moving head fixture (tested with “Lixada Mini Wash RGBW”).
2. Switch to the Virtual Console, add a XY pad and add the fixture to it.
3. Connect an external input in absolute mode (default) to the pan and tilt channels, but leave the corresponding fine channels without external input (tested with a HID joystick and with a second QLC+ instance via OSC on localhost).
4. Switch to “Operate” mode, open the DMX monitor and input on the external controls.
**Result:**
The non-fine (coarse) channels move according to `input - 1`, but the values of the fine channels always equal to `255 - coarseValue`.
**Expected result:**
The absolute external input to the coarse channels is output correctly and does not affect the value of the fine channels. …
> virtualconsole/xypad: fix external input to coarse channels affecting fine channels

- engine/src/cuestack.cpp
- ui/src/cuestackmodel.cpp
- ui/src/cuestackmodel.h
**Disclaimer:**
- This issue was neither discovered nor reported by me, but via the [QLC+ forum]( https://www.qlcplus.org/forum/viewtopic.php?t=18592).
- I have never used the “cue stack” feature of QLC+ myself. Furthermore, since scenes and chasers are the better option in most cases, it is not going to be available in QLC+ v5. Therefore, it might already be considered “deprecated” in v4.
**Steps to Reproduce:**
0. _Note: If QLC+ uses Qt5, this issue does not occur. It only seems to happen on Qt6 QLC+ builds._
1. Open a new QLC+ workspace.
2. On the “Simple Desk” page, add at least three cues in the same cue stack.
3. Use the arrow buttons to play the cues forwards or backwards, respectively.
**Result:**
Every cue played since the last “stop” is marked with a small triangle.
**Expected …
> [v4/Qt6] Cue Stack: fix marker of currently active cue

- ui/src/inputselectionwidget.cpp
Summary of Changes:
  - Save feedback values before changing input source value
  - Set feedback values that was saved after changing input source value
Related Issues: #1784
> #1784 feat/persist-feedback-when-changing-input-source-of-vc-controls
